microsoftgraph/microsoft-graph-explorer-v4

- azure-pipelines.yml
- package.json
Runs test and linting in CI environment
N/A
N/A
N/A
[#19](https://github.com/microsoftgraph/microsoft-graph-explorer-v2/issues/19)
> Runs test and linting in CI environment

- src/app/services/actions/query-action-creators.ts
- src/app/services/constants.ts
- src/app/views/authentication/Authentication.tsx
- src/app/views/authentication/authentication.scss
- src/app/views/authentication/profile/Profile.tsx
- src/app/views/query-runner/QueryRunner.tsx
- src/types/query-runner.ts
Fetches the image on log in and feeds it to the authentication component
> Profile component

- src/app/services/actions/query-action-creators.ts
- src/app/services/constants.ts
- src/app/views/authentication/Authentication.tsx
- src/app/views/authentication/authentication.scss
- src/app/views/authentication/profile/Profile.tsx
- src/app/views/common/submit-button/SubmitButton.tsx
- src/app/views/query-runner/QueryRunner.tsx
- src/types/authentication.ts
- src/types/query-runner.ts
- src/types/submit-button.ts
Moves the sign-in action and profile to their own components
Adds a reusable button that accepts the progress status and displays a spinner to show that there is action happening
> Sign in action

- src/app/views/authentication/profile/Profile.tsx
- src/app/views/query-runner/QueryRunner.tsx
- src/app/views/query-runner/request/Request.tsx
- src/index.tsx
- src/types/profile.ts
- src/types/query-runner.ts
- src/types/request.ts
> add missing types

- .babelrc
- jest.config.js
- package.json
> declutter package.json

- .prettierrc
- package.json
- src/app/views/query-runner/request/RequestHeaders.tsx
- tslint.json
Adds prettier to ensure the codebase has a consistent style without devs ever having to post a nit-picky comment on a code review ever again!
run `yarn prettier`
> add prettier

- CONTRIBUTING.md
- README.md
> add readme file and contribution file

- src/app/views/App.tsx
Adds a banner in the TryIt improvement
N/A
N/A
Fixes [107](https://github.com/microsoftgraph/microsoft-graph-explorer-v2/issues/107)
> Adds informational banner

- src/app/views/query-runner/util/iframe-message-parser.ts
Fixes multiple headers shown in the TryIt experience
N/A
N/A
N/A
> Fixes multiple headers showing

- src/app/views/authentication/authentication.scss
- src/app/views/authentication/profile/Profile.tsx
Removes the overlap of the profile image on the user details
* Log - in
* Notice that there is a visible gap between your name and your profile picture
> fixes profile image overlap

- src/app/views/App.tsx
- src/styles/index.scss
Adds a more visible outline on focused items
N/A
* Open Graph Explorer
* Tab through components
* Observe a blue-ish outline on focused items
Fixes #138
> Outlines focused items

- src/app/views/App.tsx
Experiment to check that the theme changes without reload
> [experiment] theme change

- src/app/views/query-runner/util/iframe-message-parser.spec.ts
- src/app/views/query-runner/util/iframe-message-parser.ts
Fixes the http parser breaking when parsing beta endpoints.
Fixes #159
> Fixes the parser breaking when parsing beta endpoints

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Adds issue templates so as to standardise the issue formats.
> Adds feature request and bug report templates

- src/app/views/App.tsx
Fixes responsiveness bug, where the app's width was being expanded.
N/A
N/A
* Launch Graph Explorer.
* Add the query parameter `locale=en-us` to simulate try it mode.
* Observe that the app's width is not increased.
> Specifies columns for small screens

- src/app/views/query-runner/request/Request.tsx
> Removes JSX closing tag

- src/app/views/query-response/query-response.scss
- src/app/views/query-runner/QueryRunner.tsx
- src/types/query-runner.ts
Shows the headers tab on GE Complete
FIxes #194
> show the headers tab

- src/app/views/App.styles.ts
- src/app/views/App.tsx
Attempt at fixing the layout overlfow in the -tst environment.
N/A
Sets the height to 1024 pixels because that is the height of the container in -tst.
N/A
> Set's the height to 1024px

- src/app/views/authentication/Authentication.styles.ts
- src/app/views/authentication/Authentication.tsx
- src/app/views/authentication/profile/Profile.tsx
- src/messages/en-US.json
> adds descriptive text when the user's not logged in

- src/app/views/App.tsx
- src/app/views/opt-in-out-banner/Banner.tsx
- src/messages/en-US.json
Fixes #245 
Fixes #246
New preview button position
New terms of use message
> Task: sidebar enhancements

- src/app/services/graph-constants.ts
Reduces the list of default user scopes
N/A
N/A
N/A
> Reduces the list of default user scopes

- src/app/views/query-runner/request/Request.tsx
- src/messages/en-US.json
> Show permissions

- src/app/views/query-runner/request/permissions/Permission.tsx
> fixes problem with permissions tab

- src/app/views/query-response/QueryResponse.tsx
- src/app/views/query-response/pivot-items/pivot-items.tsx
Refactor PivotItems from `QueryResponse.tsx` to a separate file
N/A
Placing the PivotItems in a separate file improves the readability of the QueryResponse component.
N/A
> Task refactor pivot items

- src/app/views/sidebar/history/History.tsx
Changes the icon from the caret down to a more familiar 3 dots.
Closes #229 
* Run a query
* Go to the history tab
* Notice 3 dots next to the history item
> Task: change icon type for history items

- src/app/services/graph-client/msal-service.ts
Attempts to fix blocked popups in edge-dev
Fixes #313
> [attempt] changes acquireTokenPopup to acquireTokenSilent

- src/app/views/App.styles.ts
Changes the colour of the links to blue
Fixes #303 
N/A
* Load GE
* Notice terms and conditions links are more visible
> Task: Make Terms and conditions links blue

- src/app/services/graph-client/msal-service.ts
calls acquiretoken popup when silent fails
> calls acquiretoken popup when silent fails

- package.json
> bumps up version to 4.0.4

- package-lock.json
- src/app/services/actions/auth-action-creators.ts
- src/app/views/App.tsx
> Task: enable tryit login

- src/app/views/settings/Settings.tsx
> fixed a typo: themeAtionCreators -> themeActionCreators

- src/app/views/query-runner/util/iframe-message-parser.ts
> fixed a wording issue: isDelimeter ->isDelimiter

- azure-pipelines.yml
pauses deployment steps pending variables....
> Disables deployment steps for Azure Pipelines

- README.md
Describes the use of the environment file to store the client ID variable
Fixes #323
> Describes use of .env file to save client ID

- src/app/services/actions/query-action-creator-util.ts
> Task: Show counts on requests with $count

- src/app/views/query-runner/QueryInput.tsx
Hitting the enter key in the query url text field runs the query
Fixes #380
> Fix: Run query when enter key is pressed

- src/app/views/App.tsx
Brings back the missing settings icon to the try it experience to allow for logging out.
> Fix: Try-it logout

- src/app/views/App.styles.ts
- src/messages/GE.json
Changes terms of use message 
Adds an !important flag to the links colour to ensure the colour doesn't change
Fixes #381
> Fix: Terms of use

- azure-pipelines.yml
Sends a teams notification if the pipeline fails
> Task: Pipeline failure teams notification

- package.json
Attempts to fix sign in errors encountered by users who use edge
Fixes #357 
Fixes #396 
Updates to using msal: 1.2.1
> Fix: Sign in errors in edge browsers

- src/app/views/sidebar/history/History.tsx
- src/messages/GE.json
> Task: adds localisation for history delete

- src/app/views/authentication/profile/Profile.tsx
Increases spacing on the primary text to make words that have hanging letters more visible
Fixes #412 
N/A
> Fix: Spacing on profile

- src/app/views/App.tsx
- src/messages/GE.json
Changes the wording and colour of the information bar in the try-it experience
Fixes #411 
N/A
> Task: change wording and colour on info bar in try-it

- src/app/views/query-runner/QueryInput.tsx
> Fix: show long endpoints

- src/app/views/sidebar/history/History.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
> Fix: Searchbox focus fix

- src/app/views/query-response/pivot-items/pivot-items.tsx
- src/app/views/query-runner/QueryInput.tsx
- src/app/views/query-runner/request/Request.tsx
- src/app/views/query-runner/request/permissions/Permission.tsx
- src/messages/GE.json
> Task: fix enter - add tooltips

- src/app/views/common/monaco/Monaco.tsx
> Fix: Try it scroll bars

- src/app/views/App.tsx
> Task: Remove redundant authentication

- src/app/views/App.tsx
Bumps the breakpoint to 1260px
> Task: responsive sidebar

- src/app/views/query-runner/request/headers/HeadersList.tsx
- src/app/views/query-runner/request/headers/RequestHeaders.tsx
- src/types/request.ts
Adds missing key value pair localisations
> Task: Add missing locs

- src/app/views/App.tsx
- src/app/views/authentication/profile/Profile.tsx
- src/app/views/common/share.ts
- src/app/views/query-runner/request/permissions/Permission.tsx
- src/app/views/settings/Settings.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #521 
Fixes #511 
Fixes #520 
Fixes #512
> Task: GA bug bash

- src/index.tsx
Loading the application in the pt-br locale was breaking.
Changed the br in the locale to pt to reflect the language not the dialect and it worked
> Fix: Portuguese locale not loading

- src/app/views/query-runner/request/permissions/Permission.tsx
> Task: Refine permission column sizes

- src/app/views/sidebar/sample-queries/SampleQueries.tsx
The picture here speaks volumes :-)
> Fix: MIsaligned sidebar elements

- src/app/services/graph-client/msal-service.ts
Change the locale of the popup request
> Task: localised login popup

- src/app/views/query-runner/QueryInput.tsx
Make Run Query btn responsive.
> Fix: Make Run Query button responsive

- src/app/views/query-runner/request/permissions/Permission.tsx
Re-renders the list once a user consents to permissions
> Task: Refresh permissions when permissions are consented

- azure-pipelines.yml
- package-lock.json
- src/app/views/query-runner/QueryRunner.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- src/telemetry/telemetry.ts
Reactivates app insights
Tracks when a query is ran
N/A
N/A
* Open devtools
* Hit run query
* Notice a track network call
> Task: reactivate app insights

- src/app/views/query-runner/QueryRunner.tsx
- src/app/views/query-runner/query-input/AutoComplete.tsx
- src/app/views/query-runner/query-input/QueryInput.styles.ts
- src/app/views/query-runner/query-input/QueryInput.tsx
- src/app/views/query-runner/query-input/index.ts
- src/app/views/query-runner/query-input/util.ts
- src/types/auto-complete.ts
- src/types/query-runner.ts
Creates an autocomplete component that hosts the suggestions
- Shows the query parameters for the query
- Shows the options within the selected parameter
- Options are chosen using the tab key or clicking the choice
- Currently, this code fetches the query parameters when the '? - question mark' is hit. Then provides the properties of the query parameters when the '= - equal sign' is hit. 
- Having selected the property, hitting the ', - comma' shows the properties again
- Choosing the '& - ampersand' shows the query parameters again
- Search as you type and tab similar to a code editor's autocomplete
- ...
> Task: Create autocomplete component

- src/app/views/query-response/QueryResponse.tsx
- src/app/views/query-response/pivot-items/pivot-items.tsx
- src/app/views/query-runner/request/Request.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- Changed the header text on the request and response area to make it more responsive and enable easy navigation for low vision users when the page is resized to 200%.
request area with page resized to 200%
response area, with page resized to 200%
> Task: change header text

- src/messages/GE_de-DE.json
- src/messages/GE_es-ES.json
- src/messages/GE_fr-FR.json
- src/messages/GE_ja-JP.json
- src/messages/GE_pt-BR.json
- src/messages/GE_ru-RU.json
- src/messages/GE_zh-CN.json
HandBack of localized GE.jsons.
> HB of localized GE.jsons

- .github/workflows/azure-static-web-apps-green-ocean-0685f0110.yml
> change deployment settings

- src/app/views/app-sections/StatusMessages.tsx
Fix message truncation on the tip message bar
Fixes #678 
> Fix: Message bar truncation

- src/app/services/actions/query-action-creator-util.ts
- src/app/views/common/monaco/Monaco.tsx
- src/app/views/query-response/pivot-items/pivot-items.tsx
Fixes #670 
Anonymous
Logged in
* Run this query: https://microsoftgraph.chinacloudapi.cn/beta/$metadata
* Receive response
> Fix: sovereign clouds metadata

- src/app/views/sidebar/history/history-utils.ts
Fixes #674 
Shows only the history items that fit the threshold, delete the others
> Feature: History items ttl

- src/app/views/query-response/pivot-items/pivot-items.tsx
An extra code snippets tab was visible .
This fix removes it
> Fix: remove unnecessary code snippets tab

- src/app/views/authentication/Authentication.tsx
The setContent method has been depracated, we need to remove it for security review
> Task: removes depracated setConsent method

- src/app/views/query-runner/QueryRunner.tsx
> Remove telemetry logging for run query events

- CHANGELOG.md
- package.json
Version needs to be bumped - it is not auto-incremented.
> Bump version to 4.1.8 for disable query telemetry

- package-lock.json
- package.json
> chore(release): 4.1.9

- src/app/views/query-runner/query-input/AutoComplete.tsx
In case you delete something and want to retrigger the suggestions, you can use `CMD+.` / `CTRL+.` / `CTRL+space` / `CMD+space`
> Task: retrigger suggestions using key combinations

- src/app/views/sidebar/history/History.tsx
- src/messages/GE.json
Add a string on the history tab letting users know about auto deletion of items older than 30 days.
Fixes #717
> Task: display history items ttl message

- src/app/views/query-runner/query-input/AutoComplete.tsx
Capture telemetry for selected autocomplete suggestions.
> Capture telemetry for autocomplete suggestions

- .vscode/settings.json
- package-lock.json
- package.json
- src/app/services/actions/adaptive-cards-action-creator.ts
Updates adaptive card templating library to the latest.
Removes the dollar sign that appears in the new Adaptive Cards templating library.
Fixes #730 
Previously...
Updated...
> Fix: breaking change with the adaptive cards templating library

- package-lock.json
- package.json
> Release: October 2020

- src/app/utils/query-url-sanitization.ts
- src/app/utils/sample-url-generation.ts
- src/app/views/query-response/QueryResponse.tsx
- src/app/views/query-response/pivot-items/pivot-items.tsx
- src/app/views/query-response/snippets/snippets-helper.tsx
- src/app/views/query-runner/QueryRunner.tsx
- src/app/views/query-runner/query-input/AutoComplete.tsx
- src/app/views/query-runner/request/Request.tsx
- src/app/views/sidebar/history/History.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- src/tests/utils/sanitize-url.spec.tsx
Calls the api with the url signature
> Task: use url signatures

- src/app/services/actions/autocomplete-action-creators.ts
- src/app/utils/query-url-sanitization.ts
- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
- src/modules/suggestions/ISuggestions.ts
- src/modules/suggestions/cache-provider.ts
- src/modules/suggestions/suggestions.ts
> Task: append version number

- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
Added aria-label to the Query Input text field
> Fix: add aria-label

- package-lock.json
- package.json
- src/app/views/query-runner/request/permissions/Permission.tsx
- src/app/views/sidebar/history/History.tsx
> Release: December 2020

- src/app/views/query-runner/request/permissions/PanelList.tsx
- src/app/views/query-runner/request/permissions/TabList.tsx
Consented permissions were not being shown as consented.
> fix: permissions consent

- src/app/views/query-runner/QueryRunner.tsx
When the create page template changes in the request body, it fails the json format testing. It should not pass since it is HTML content and not a JSON body.
The fix changes the JSON content validation to only work on the content that is a JSON string and content that has not been labeled using the content-type header.
Fixes #836 
N/A
N/A
* Log in and run the create page query after getting a section id
* Run the create page query before editing it
* Run the create page query after editing it
> fix: intermittent create page error

- src/app/views/sidebar/sample-queries/SampleQueries.tsx
Adjust the column width to clearly display a sample query's documentation link
_Update_
_Previously_
> Fix: adjust column width

- package-lock.json
- package.json
> Release: February 2021

- package-lock.json
- package.json
- src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx
> Release: february 2021 2

- src/messages/GE_de-DE.json
- src/messages/GE_es-ES.json
- src/messages/GE_fr-FR.json
- src/messages/GE_ja-JP.json
- src/messages/GE_pt-BR.json
- src/messages/GE_ru-RU.json
- src/messages/GE_zh-CN.json
> HB of localized GE jsons

- src/messages/GE_de-DE.json
- src/messages/GE_es-ES.json
- src/messages/GE_fr-FR.json
- src/messages/GE_ja-JP.json
- src/messages/GE_pt-BR.json
- src/messages/GE_ru-RU.json
- src/messages/GE_zh-CN.json
Co-authored-by: OfficeGlobal <OfficeGlobal@microsoft.com>
> HB of localized GE.jsons (#880)

- src/telemetry/component-names.ts
Fixes linting errors preventing the pipeline from running
> Release: april 2021 v2

- azure-pipelines.yml
Add Credential Scanner (aka CredScan), a tool used to identify credential leaks
fixes #506
> Task: Add Cred Scan

- src/app/views/query-runner/query-input/QueryInput.tsx
- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
- src/messages/GE.json
Fixes #643
* Delete the sample query
* Attempt to run the query
* Notice the button is disabled and a message is presented
> Fix: prevent running empty requests

- .github/CODEOWNERS
- src/types/query-runner.ts
Adds reviewers to a PR automatically
> Task: add code-owners

- src/app/views/settings/Settings.tsx
- src/telemetry/component-names.ts
Add telemetry for clicks on the **Report an issue** link
> Task: Add telemetry for Report an Issue Link

- package-lock.json
- package.json
- src/app/services/actions/theme-action-creator.ts
- src/app/utils/status-message.ts
- src/app/views/App.tsx
- src/app/views/app-sections/TermsOfUseMessage.tsx
- src/app/views/query-response/headers/ResponseHeaders.tsx
- src/app/views/query-response/pivot-items/pivot-items.tsx
- src/app/views/query-response/snippets/snippets-helper.tsx
- src/app/views/query-runner/query-input/QueryInput.tsx
- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
- src/app/views/query-runner/query-input/auto-complete/auto-complete.styles.ts
- src/app/views/query-runner/query-runner.scss
- src/app/views/query-runner/request/auth/Auth.tsx
- src/app/views/query-runner/request/headers/RequestHeaders.tsx
- src/app/views/query-runner/request/permissions/TabList.tsx
- src/app/views/settings/Settings.tsx
- src/app/views/sidebar/Sidebar.styles.ts
- src/app/views/sidebar/history/History.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- src/app/views/sidebar/sample-queries/tokens.ts
- src/index.tsx
- src/messages/GE.json
- src/tests/utils/proxy-url.spec.ts
- src/themes/theme-utils.ts
- src/types/auto-complete.ts
> Release: August 2021

- package-lock.json
- package.json
- src/tests/services/actions/profile-action-creators.spec.tsx
Fixes failing profile test that prevents a successful build
> Task: Fix failing tests

- src/app/views/authentication/AuthenticationErrorsHints.ts
- src/app/views/query-response/QueryResponse.tsx
Adds overflow item to the response area
> Response-area

- .github/workflows/linter.yml
Checks code for linting errors not captured during development
> Task: add linter github workflow

- src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #1209 
On sample queries, click on any sample query
Type a phrase in the sample queries search box.
Sample queries are successfully retrieved
> validate index of selected query

- package-lock.json
- package.json
This PR contains updates for various packages on GE
> Chore: (Dependabot) Update packages

- package-lock.json
- package.json
- src/modules/authentication/AuthenticationWrapper.ts
Reverts microsoftgraph/microsoft-graph-explorer-v4#1229
> Revert "Chore(deps): Bump @azure/msal-browser from 2.12.0 to 2.19.0"

- .github/dependabot.yml
Daily dependabot PRs are overwhelming :-(
Changing it to monthly
> change the frequency of dependabot updates

- .github/workflows/linter.yml
Adds a build step to the tour workflow
> Task: add build step to linter workflow

- src/app/views/sidebar/Sidebar.tsx
Remove resources tab till we are ready to deploy
> Task: Remove resources tab

- config/webpack.config.js
- package-lock.json
- package.json
- src/app/services/actions/query-action-creator-util.ts
- src/app/services/actions/query-action-creators.ts
- src/app/services/actions/snippet-action-creator.ts
- src/app/services/graph-constants.ts
- src/app/views/app-sections/ResponseMessages.tsx
- src/app/views/query-response/headers/ResponseHeaders.tsx
- src/app/views/query-response/response/Response.tsx
- src/app/views/query-response/snippets/Snippets.tsx
- src/messages/GE.json
- src/messages/GE_de-DE.json
- src/messages/GE_es-ES.json
- src/messages/GE_fr-FR.json
- src/messages/GE_ja-JP.json
- src/messages/GE_pt-BR.json
- src/messages/GE_ru-RU.json
- src/messages/GE_zh-CN.json
- tsconfig.json
> Release 01-2022

- src/app/views/sidebar/Sidebar.styles.ts
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
> Update documentation link icon

- src/app/views/query-runner/request/request.scss
> Fix external text overflowing on feedback button

- src/app/views/sidebar/Sidebar.tsx
> Hide resources tab

- src/app/views/sidebar/resource-explorer/ResourceLink.tsx
> Fix kebab menu on resource explorer

- src/app/views/sidebar/sample-queries/SampleQueries.tsx
removes the text that can be seen on the Html method badges
Fixes #1432
> Enhancement: Remove weird text on html method badges 

- .github/CODEOWNERS
> add new code owner

- src/app/services/reducers/query-runner-reducers.ts
- src/app/utils/query-url-sanitization.ts
Solves #1480 
Error is displayed under the query input and none is displayed on the console
Page does not crash when a sample query is selected
> decode url within a try catch

- src/app/utils/string-operations.ts
- src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
- src/app/views/sidebar/resource-explorer/resource-explorer.utils.ts
- src/tests/utils/resource-payload-filter.spec.ts
>  Search capability for all nodes of the tree

- .github/workflows/azure-static-web-apps-jolly-sand-0ac78c710.yml
- azure-pipelines.yml
- src/app/views/query-runner/request/feedback/campaignDefinitions.ts
> Task: adjust feedback popup time

- azure-pipelines.yml
> Chore: change build agent

- jest.config.js
> Tests: skip spec.tsx files

- jest.config.js
> fix:  Accessibility test

- src/app/views/authentication/Authentication.tsx
- src/modules/authentication/AuthenticationWrapper.ts
- src/modules/authentication/authentication-error-hints.ts
Fixes authentication error handling
> Fix: Authentication error handling

- package-lock.json
- package.json
- src/app/services/actions/snippet-action-creator.ts
Fixes bug with code snippet generation
> Release: 4.18.1

- package-lock.json
- package.json
- src/app/services/actions/query-action-creator-util.ts
- src/app/services/graph-client/graph-client.ts
- src/app/services/graph-client/index.ts
- src/modules/authentication/AuthenticationWrapper.ts
update `@microsoft/microsoft-graph-client` to `v3.0.2`
Fixes #1545
> Chore: Update MsGraph JavaScript SDK

- src/app/services/graph-constants.ts
> Add query resulting in CORS error to list for the appropriate message to be displayed

- package-lock.json
- package.json
- src/app/views/query-runner/request/permissions/Permission.tsx
Reduces the list of pending updates
> Task: Package updates

- src/app/utils/version.ts
Fixes #1668 
Click on Resources tab (or any component that is tracked)
Open the Network tab
Click on the 'track': 
On the payload, expand tags. 
Notice that the build information is 5.0.1, which is correct
> fixes build information for feedback and telemetry

- src/app/views/query-runner/request/Request.tsx
Fixes #1675 
Resize the request section to the top
Notice that all contents of the request resize with the resize handler
> Fix: Request layout

- config/webpack.config.js
- src/app/views/query-response/snippets/Snippets.tsx
- src/app/views/query-response/snippets/snippets-helper.tsx
- src/telemetry/component-names.ts
Closes #1715 
Remove Objective C from the list of supported languages for code snippets
> Remove Objective C from list of code snippets languages

- src/app/views/query-response/QueryResponse.tsx
- src/app/views/query-runner/request/Request.tsx
- src/app/views/sidebar/Sidebar.tsx
- src/messages/GE.json
Fixes #1757
Ensures overflow buttons have an aria-label
> Fix: Add overflow aria-label

- src/messages/GE.json
- src/messages/GE_de-DE.json
- src/messages/GE_es-ES.json
- src/messages/GE_fr-FR.json
- src/messages/GE_ja-JP.json
- src/messages/GE_pt-BR.json
- src/messages/GE_ru-RU.json
- src/messages/GE_zh-CN.json
> Editorial changes on the help button dropdown

- src/app/views/sidebar/history/History.tsx
- src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- src/app/views/sidebar/sidebar-utils/SearchResult.tsx
- src/messages/GE.json
> Add search results information

- src/app/views/main-header/FeedbackButton.tsx
- src/app/views/main-header/MainHeader.tsx
- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
> Remove experimental code

- src/app/views/main-header/Help.tsx
- src/app/views/main-header/settings/Settings.tsx
Fix telemetry not being collected for header menu items.
> Use correct event to trigger collection of menu item click telemetry

- src/app/views/query-runner/QueryRunner.styles.ts
- src/app/views/query-runner/query-input/QueryInput.tsx
Fixes #1931 
This PR:
Current query input:
Notice that the query textbox has most of the available space
Resize the page. Notice that the query textbox still covers most of the space available
> Disable shrinking on the query textbox

- src/app/views/query-runner/request/permissions/util.ts
Fixes #2022 
Load GE locally
Click on sign  in
Notice that you are signed in without an issue
Click on Network tab and experiment with slow networks
Notice that sign in still works
> Validate permissions and consented scopes before accessing them

- src/app/views/query-response/pivot-items/pivot-items.tsx
Fixes #2027 
On localhost the font sizes appear the same but on prod they are different.
Best way to test would be on -tst...
> Fix: Response area pivot font sizes

- src/app/views/query-runner/QueryRunner.styles.ts
- src/app/views/query-runner/query-input/QueryInput.tsx
- src/app/views/query-runner/query-runner.scss
Closes #2058 
Observe enhancement
> Reduce share query size

- src/app/services/actions/query-action-creator-util.ts
- src/app/services/actions/query-action-creators.ts
> Fix: Fix error response status

- src/app/views/query-response/QueryResponse.tsx
- src/app/views/query-response/query-response.scss
> Fix: Localize 'Expand' string

- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
Prevent unintentional display of suggestions
> Fix: Prevent unintentional display of suggestions

- src/app/services/actions/query-action-creator-util.ts
> Fix: failing api calls

- .github/workflows/cut-release.yml
Fixes syntax error in last step of release workflow
> Fix: Cut release to master

- src/messages/GE.json
Closes #1949 
Load the app
Notice that Modify Permissions tab no longer has 'preview'
> Take Modify Permissions out of preview

- package-lock.json
- package.json
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- src/app/views/sidebar/sample-queries/sample-query-utils.ts
Fixes #2040 
1. Open the URL: https://jolly-sand-0ac78c710-2118.centralus.azurestaticapps.net in Edge Dev.
2. Navigate to Sample queries tab item further navigate to getting started (8)
2. Navigate to the Data grid in scan mode.
3. Observe that in scan mode, Narrator focus should not go on unnecessary(empty) data cells while navigating with both down/up arrow key.
> Task: fix accessibility unnecessary empty data scans

- package-lock.json
- package.json
- src/app/views/App.spec.tsx
- src/setupTests.ts
> Fix: Failing tests

- src/app/utils/resources/resources-filter.ts
Closes #2152 
Prevent deep copy in recursion function
> Fix: stop recursive deep copy

- src/app/services/actions/permissions-action-creator.ts
- src/messages/GE.json
Closes #2184 
Sign in with an admin account
Click on Modify Permissions tab and consent to any permission
Notice that a status message is set
> Fix: Add consent status for successful consent

- src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx
- src/themes/dark.ts
- src/themes/high-contrast.ts
- src/themes/light.ts
Fixes #2018 
This problem is only on production. We'll have to deploy to the staging environment with the header and footer injected to confirm that the fix works
Run the query https://graph.microsoft.com/v1.0/sites/root
Click on `Adaptive Cards` tab
See fix
> Fix: Adaptive cards color on dark mode

- src/app/services/actions/request-history-action-creators.spec.ts
- src/app/services/actions/request-history-action-creators.ts
> Fix: View history items

- README.md
> Task: Add Graph Support Info on README.md

- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
Fixes #2412 
The query URL was not being updated for path segments that are not in the resource tree
Click on the query textbox and press Enter on your keyboard
Now append /mailboxSettings to the query
Click on RunQuery
Notice that the current query runs
> Fix: Previous query error

- .devcontainer/devcontainer.json
Enable a one-click development environment using a [VSCode devcontainer](https://code.visualstudio.com/docs/devcontainers/containers)
* Have Docker Desktop installed and use Linux containers
* Open this branch in VSCode.
* Ctrl+Shift+P and select "Reopen in Container"
> Add a devcontainer to the repo

- src/app/views/query-response/snippets/snippets-helper.tsx
- src/app/views/query-runner/request/permissions/PanelList.tsx
- src/app/views/query-runner/request/permissions/TabList.tsx
- src/messages/GE.json
Closes #2429 
Disable your internet connection after loading the app
Open the permissions tab
See the error displayed
> Enhancement: Add correct error message for snippets and permissions

- azure-pipelines.yml
- package-lock.json
- package.json
- src/app/views/query-runner/request/permissions/TabList.tsx
- src/tests/ui/anonymous-experiences/request.spec.ts
- src/tests/ui/authenticated-experiences/authenticated-experiences.spec.ts
> Chore: Update to 8.1.0

- src/app/views/sidebar/resource-explorer/ResourceLink.tsx
- src/messages/GE.json
Changes "remove" to "Remove from collection" in the resource explorer links
> Chore: change "remove" aria label

- src/app/services/reducers/collections-reducer.spec.ts
Fixes an oversight in the collections tests
> Fix: Collections reducer failing test logic

- src/app/services/actions/collections-action-creators.spec.ts
- src/app/services/actions/resource-explorer-action-creators.spec.ts
- src/app/services/reducers/collections-reducer.spec.ts
- src/app/services/reducers/resources-reducer.spec.ts
- src/app/views/sidebar/resource-explorer/resourcelink.utils.spec.ts
- src/modules/cache/resources.cache.spec.ts
- src/types/resources.ts
To be consistent with HTTP, all methods should be uppercase
> Chore: Uppercase methods

- .github/fabricbot.json
> Fix: Remove use of external label

- package-lock.json
- package.json
> Fix: Update dependencies with hig security risk

- package-lock.json
- package.json
Reverts microsoftgraph/microsoft-graph-explorer-v4#2724
> Revert "Chore(deps-dev): Bump @types/react from 18.2.14 to 18.2.18"

- src/app/utils/query-url-sanitization.ts
- src/tests/ui/anonymous-experiences/request.spec.ts
Fixes #2736 
Clear the content of the query URL and type the query: `https://graph.microsoft.com/v1.0/tenantRelationships/microsoft.graph.findTenantInformationByDomainName(domainName='{domainName}')`
Notice that the UI is still responsive
> Fix: Sanitization regex

- package-lock.json
- package.json
> Chore: Update to 9.2.0

- .github/policies/resourceManagement.yml
> Fix: Add triage event responder

- src/app/views/query-response/snippets/Snippets.tsx
- src/app/views/query-response/snippets/snippets-helper.tsx
Fixes #2826 
* Check out branch
* Navigate to Code snippets tab
* Select CLI tab
* Observe changes
> Fix: Update CLI tab to use uppercase

- config/webpack.config.js
- package-lock.json
- package.json
- src/app/services/hooks/usePopups.ts
- src/app/views/common/error-boundary/ErrorBoundary.tsx
- src/app/views/common/lazy-loader/component-registry/index.tsx
- src/app/views/common/lazy-loader/component-registry/popups.tsx
The portal is blocking the chunks. This is a temporary stop until we can figure out how to have the portal support the chunking
> Release: 9.3.1

- package-lock.json
- package.json
- src/app/views/query-runner/request/Request.tsx
Adds accessibility fix 
Updates to 9.3.2
> Chore: Hotfix release 9.3.2

- .github/policies/resourceManagement.yml
> Fix: Remove ToTriage label when an issue has been assigned

- .github/workflows/linter.yml
- package-lock.json
- package.json
> Chore: Update to 9.4.0

- azure-pipelines.yml
- config/webpackDevServer.config.js
- src/app/views/query-response/QueryResponse.tsx
- src/app/views/query-runner/request/Request.tsx
- src/messages/GE.json
- src/styles/index.scss
- src/tests/ui/anonymous-experiences/header.spec.ts
- src/tests/ui/anonymous-experiences/sidebar.spec.ts
- src/tests/ui/responsiveness/mobile-responsive.spec.ts
Fixes #2749
These tests needed to be updated.
The resize observer loop limit error also interferes sometimes as it displays as an overlay on the whole screen.
* Observe tests on azure pipeline
> Fix: Failing playwright UI tests

- package-lock.json
- package.json
- src/app/services/reducers/permissions-reducer.spec.ts
- src/app/services/reducers/permissions-reducer.ts
>  Chore: Update 9.6.0 

- package-lock.json
- package.json
> Chore: update to 9.7.0

- package-lock.json
- package.json
Reverts microsoftgraph/microsoft-graph-explorer-v4#3056 as it has a breaking change
> Revert "Chore(deps): Bump @babel/core from 7.23.3 to 7.24.1"

- package-lock.json
- package.json
> Chore: Update to 9.8.0

- src/modules/authentication/AuthenticationWrapper.ts
A query parameter has been added to cater for the migrated values
>  Chore: app migration 

- package-lock.json
- package.json
> Chore: Update to 10.0.0

- package-lock.json
- package.json
> Chore: Release 10.2.1

- .vscode/settings.json
- package-lock.json
- package.json
- src/app/services/context/validation-context/ValidationProvider.tsx
- src/app/views/app-sections/StatusMessages.tsx
- src/app/views/app-sections/TermsOfUseMessage.tsx
- src/app/views/authentication/Authentication.tsx
- src/app/views/main-header/FeedbackButton.tsx
- src/app/views/main-header/Help.tsx
- src/app/views/main-header/MainHeader.tsx
- src/app/views/main-header/settings/Settings.tsx
- src/app/views/query-response/QueryResponse.tsx
- src/app/views/query-response/pivot-items/pivot-items.tsx
- src/app/views/query-response/queryResponse.styles.ts
- src/app/views/query-response/response/Response.tsx
- src/app/views/query-response/response/ResponseMessages.tsx
- src/app/views/query-runner/QueryRunner.tsx
- src/app/views/query-runner/query-input/QueryInput.tsx
- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
- src/app/views/query-runner/query-input/auto-complete/suffix/SuffixRenderer.tsx
- src/app/views/query-runner/query-input/auto-complete/use-previous.ts
- src/app/views/query-runner/request/Request.tsx
- src/app/views/query-runner/request/body/RequestBody.tsx
- src/app/views/query-runner/request/feedback/FeedbackForm.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
> fix: select only the required values from state and useEffect to get description error message

- src/app/views/App.tsx
- src/app/views/sidebar/SidebarV9.tsx
> feat: update the sidebar tabs to use fluent UI v9

- src/app/views/common/copy-button/CopyButtonV9.tsx
- src/app/views/query-runner/request/auth/AuthV9.tsx
- Fixes layout issues with the auth tab content
- Uses Text component features to style the auth token text
This pull request includes various changes to improve code readability and maintainability in the `CopyButtonV9.tsx` and `AuthV9.tsx` components. The most important changes include reordering imports, updating prop types, and enhancing the styling and layout.
* [`src/app/views/common/copy-button/CopyButtonV9.tsx`](diffhunk://#diff-bd4cb71eacc100510731161c5219529f86befa6f94b8370d4ca1060077bdc7ebL1-R8): Reordered imports for better readability and updated the `handleOnClick` prop type to be more specific.
* [`src/app/views/query-runner/request/auth/AuthV9.tsx`](diffhunk://#diff-9d0e82caf38783317870ee36f968f8c67915ee7ed8552399e577089d0b8d2038L1-R38): Reordered imports for better …
> fix: improve request auth tab

- src/app/views/query-runner/request/permissions/ConsentType.tsx
- src/app/views/query-runner/request/permissions/PermissionItemV9.tsx
> feat: migrate consent type component to v9

- src/app/views/query-response/pivot-items/pivot-item-v9.tsx
- src/app/views/query-runner/request/RequestV9.tsx
> Feat: Add tab icons

- src/app/views/sidebar/SidebarV9.tsx
- src/app/views/sidebar/history/History.tsx
- src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
- src/app/views/sidebar/resource-explorer/resourceExplorerStyles.ts
> feat: update sidebar component designs, fix regressions

- src/app/views/App.tsx
- src/app/views/main-header/settings/ThemeChooser.tsx
- src/app/views/sidebar/history/History.tsx
- src/index.tsx
> fix: update theming to fix flickering

- src/app/views/sidebar/resource-explorer/collection/CommonCollectionsPanel.tsx
- src/app/views/sidebar/resource-explorer/collection/Paths.styles.ts
Fixes allignment issues from #3638 
> fix: paths misalignment in collections

- .github/workflows/release-please-master.yml
This PR adds another release please workflow that specifically targets the master branch
fixes #3653 
> chore: add release please workflow targeting master

- src/app/views/query-response/pivot-items/pivot-item.tsx
- src/app/views/sidebar/resource-explorer/collection/EditScopePanel.tsx
Updates response preview icon from design feedback
> feat: update response icon

- src/app/views/sidebar/history/History.styles.ts
- src/app/views/sidebar/history/History.tsx
- src/app/views/sidebar/resource-explorer/resourceExplorerStyles.ts
- src/app/views/sidebar/sample-queries/SampleQueries.styles.ts
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #3648 
* Check out PR
* Tab through sample queries
* Tab through history items 
* Observe focus outline
> fix: sample queries and history keyboard navigation

- azure-pipelines.yml
reverts the change where the blob storage deployment was removed
> fix: add deploy to blob storage task

- src/app/services/slices/collections.slice.ts
- src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
- src/app/views/sidebar/resource-explorer/ResourceLink.tsx
- src/app/views/sidebar/resource-explorer/resourceExplorerStyles.ts
> fix: remove duplicates in collections

- src/app/services/context/popups-context/index.ts
- src/app/views/common/popups/DrawerWrapper.tsx
- src/app/views/query-response/response/ResponseDisplay.tsx
- src/app/views/query-response/snippets/Snippets.tsx
- src/app/views/query-runner/query-input/QueryInput.tsx
- src/app/views/query-runner/query-input/auto-complete/suggestion-list/SuggestionsList.styles.ts
- src/app/views/query-runner/query-input/auto-complete/suggestion-list/SuggestionsList.tsx
- src/app/views/query-runner/request/permissions/Permission.styles.ts
- src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
- src/app/views/sidebar/resource-explorer/ResourceLink.tsx
- src/app/views/sidebar/resource-explorer/collection/Paths.tsx
- src/app/views/sidebar/resource-explorer/resourceExplorerStyles.ts
- src/app/views/sidebar/resource-explorer/resourceLinkStyles.ts
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- src/messages/GE.json
Work on #3705 
Fixes
Ensure the issues listed are resolved as expected on the calm wave link
> fix: api explorer accessibility issues from test pass findings

- package-lock.json
- src/app/views/authentication/profile/Profile.tsx
- src/messages/GE.json
Fixes accessibility issues for the profile card:
Description:
- Adds use of `inertFocusTrap` to focus on the first interactive element of the profile card.
- Adds aria elements to announce the name of the signed in user when the profile card is activated.
- Adds aria elements to announce button has popup
> fix: accessibility fixes for the Profile Card

- __mocks__/@azure/msal-browser
- src/index.tsx
- src/modules/authentication/msal-app.ts
Closes #3711 
Login, then refresh/reload page. Check that user is still signed in.
> fix: ensure initialize completes before other invocations

- src/app/views/sidebar/history/History.tsx
- src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
- src/messages/GE.json
Fix https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_workitems/edit/30686/?view=edit
1. Open URL in web
3. Open Narrator.
4. Navigate till Sample Queries and search for a resource/query.
5. Search for a resource e.g users.
6. Observe the fix
> fix: announce search results

- src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
- src/app/views/sidebar/resource-explorer/ResourceLink.tsx
- src/app/views/sidebar/resource-explorer/resourceExplorerStyles.ts
- src/app/views/sidebar/resource-explorer/resourceLinkStyles.ts
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_workitems/edit/30639/?view=edit
Fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_workitems/edit/30724/?view=edit
1. Open Calm Wave URL in web
3. Navigate till API Explorer.
4. Navigate till Resources available and each of the resources.
6. Observe the fix.
1. Open Calm Wave URL in web
3. Open Narrator.
4. Navigate till Sample Queries.
5. Navigate till each query.
6. Observe the fix.
> fix: make resource tree keyboard accessible

- src/app/views/common/submit-button/SubmitButton.tsx
- src/app/views/sidebar/Sidebar.tsx
ref: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/3723#issuecomment-2750727617
> fix: sidebar height getting truncated on some screen sizes

- package-lock.json
- package.json
- src/app/views/common/monaco/monaco.scss
- src/app/views/query-response/query-response.scss
- src/app/views/query-runner/QueryRunner.tsx
- src/app/views/query-runner/query-input/QueryInput.tsx
- src/app/views/query-runner/query-runner.scss
- src/app/views/query-runner/request/request.scss
- src/messages/index.js
- src/styles/index.scss
- src/types/query-runner.ts
1. Closes #3712 
2. Fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_workitems/edit/30739/?view=edit
4. This PR also addresses build warnings arising from https://sass-lang.com/documentation/breaking-changes/import/
5. This PR also removes unused re-resize package
1. Go to provided link. Graph Explorer will load.
2. Open Narrator.
3. Using keyboard, navigate to HTTP method dropdown, and also version dropdown.
4. Observe visual indicators and announcements from Narrator.
> fix: app crashing issues from dropdown interaction

- azure-pipelines.yml
fixes #3732 
* tested on a separate branch so as to not affect the main one
> fix: update pipeline to include new service connection

- package.json
- src/app/views/sidebar/resource-explorer/collection/APICollection.tsx
- src/app/views/sidebar/resource-explorer/collection/CommonCollectionsPanel.tsx
- src/app/views/sidebar/resource-explorer/collection/EditCollectionPanel.tsx
- src/app/views/sidebar/resource-explorer/collection/EditScopePanel.tsx
- src/app/views/sidebar/resource-explorer/collection/Paths.styles.ts
- src/app/views/sidebar/resource-explorer/collection/Paths.tsx
> fix: collections action buttons moving up with few items

- src/app/views/authentication/profile/Profile.tsx
> fix: profile user image

- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
> fix: improve validation error display

- src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
> fix: share query button and documentation button are visible even when query is long

- src/app/views/main-header/Tenant.tsx
> fix: display correct tenant

- src/app/views/layout/LayoutStyles.tsx
- src/app/views/query-response/snippets/Snippets.tsx
- src/app/views/query-runner/request/Request.tsx
> fix: remove unnecessary scrollbars

- .github/policies/resourceManagement.yml
> chore: remove need for issue assignment for ToTriage label

- src/app/services/actions/autocomplete-action-creators.spec.ts
- src/app/services/actions/permissions-action-creator.spec.ts
- src/app/services/actions/resource-explorer-action-creators.spec.ts
- src/app/services/slices/samples.slice.ts
- src/app/views/sidebar/sample-queries/SampleQueries.styles.ts
- src/app/views/sidebar/sample-queries/SampleQueries.tsx
> fix: set default sample auto selection on page load globally

- src/app/views/common/monaco/Monaco.tsx
1. Fix Request Body input field not accepting continuous typing #3845 
2. Fix issue where the Request Body is not displayed when clicking a POST query on first load of Graph Explorer
> fix: request body input focus issue

- README.md
Fixing missing punctuation.
Fixing missing punctuation.
> fix: punctuation in readme
