package-lock.json, src/app/views/authentication/Authentication.tsx, src/index.tsx, src/types/authentication.ts
Authenticated state was lost when page reloadds
Tried loading the user from local storage on app load. Requiring me to use mapStateToProps which did not produce the desired result.
Currently loads the user from local storage at the authentication component level when page is reloaded using componentDidMount.
May be considered as technical debt 
* Sign in
* Reload page
* User data still available
=> bug: authenticated state lost on page reload

src/app/views/App.tsx, src/app/views/common/monaco/Monaco.tsx, src/app/views/query-runner/QueryInput.tsx
Disables focus on monaco-editor when tabbing through the application
N/A
Tabbing from one tab element to another doesn't work but users can visit that element using the direction keys. Is this compromise good enough?
* Launch Graph Explorer tab through the application.
* Launch Narrator
* Observe that you can tab through.
=> Disables focus on Monaco when tabbing

src/app/views/query-runner/QueryRunner.tsx, tslint.json
1. Sends a post message to host document to notify it that GE is ready to receive messages
2. Whitelists the following domains
```
https://docs.microsoft.com
https://review.docs.microsoft.com
https://ppe.docs.microsoft.com
https://docs.azure.cn
```
N/A
N/A
N/A
=> Notifies host document that GE is ready to receive messages

src/app/views/query-runner/request/HeadersList.tsx
Fix #70 
I have increased the minWidth, maxWidth for the columns to get the current results ☝️ 
But I don't think that will solve the issue 100% 
My second approach was to add a class name as seen below 👇 
and set the width to 45% like what the issue #70 description suggested 
this is what I get 👇 
because the parent div doesn't have a width property. 
could someone point me in the right direction?
=> increase key and value width

src/app/views/query-runner/request/RequestHeaders.tsx, src/app/views/query-runner/request/request.scss
Evenly places controls on the screen 
Moves the button closer to the other controls
* Run app
* Head to request headers
* Note that the 'add' button appears closer to the other inputs
=> evenly places controls in request headers component

src/app/services/reducers/query-runner-reducers.ts, src/app/views/App.tsx
Clears the response component on error
Setting the response to undefined / null does not affect the response component. 
* Run the profile request "/me"
* Trigger a bad request error e.g "/me/s"
* Notice the previously filled response has an empty object
=> clears the response component on error

src/app/views/query-runner/QueryInput.tsx, src/types/query-runner.ts
Disables the http version selector for customers using Graph Explorer in TryIt mode
At the moment, customers using graph explorer in TryIt mode only have access to a limited feature set. One of these limitations is that they don't need to change http verbs, therefore, this PR disables the selector control.
* Launch Graph Explorer
* Add the query parameter `?locale=en-us` to activate the TryIt mode
* Observe that the http verb selector is disabled.
Fixes #164
=> Disables the http version selector for TryIt

src/app/views/sidebar/sample-queries/SampleQueries.tsx
Previously the samples were loaded every time the samples component was loaded ignoring the fact that the results of the first call to the api actually stored the samples in the store.
This fix checks the contents of the state first and only calls the api when there are no samples in the store
Fixes #170 
* Load the app
* Notice that it displays 'Loading samples...'
* Change tabs from 'Sample Queries' to 'History' and back
* Notice that it does not display 'Loading samples...'
=> loads queries from cache after first call to api

src/index.tsx
The loading spinner on the portal does not stop spinning even after the app loads.
Now we check the existence of the html tag `<api-explorer>` that houses the loading spinner on the portal website and remove it from the DOM once Graph explorer is loaded
Fixes #178 
* Log on to the tst environment
* Observe a "starting microsoft graph explorer" spinner
* Notice that it is removed from view after loading is complete
=> removes the loading spinner from the portal

src/app/views/App.tsx
Hitting the toggle from classic adds a **/preview** to the url so as to move to the new version. This removes the additional '/' from the url
=> fixes the replacement of preview

src/index.tsx
Fixes monaco formatting bug in the -tst environment.
N/A
The bug was caused by monaco trying to load workers from a non server environment. GE is hosted in portal as a JS bundle. 
N/A
=> Set up monaco editor workers proxy

src/app/services/actions/adaptive-cards-action-creator.ts
This Pr updates the checks for the response body to prevent the attempt to render cards when the response is invalid.
The template map has also been updated to fix potential issues with request mappings. 
The '/' is added to perform better matching so that we don't try to get a template if the url simply has the phrase 'me'.
* Perform a request on that returns a 404 error
* You should see the message "Adaptive card for this Response is not available"
=> Fix displaying of cards on error response

src/app/services/actions/permissions-action-creator.ts
Updates how scope values are consumed as they will be returned as an array of objects from the Permissions API.
Given a sample request for example: 
`/api/GraphExplorerPermissions?requesturl=/me/memberof&method=GET&scopetype=DelegatedWork`
The returned scopes will be of the format:
`[ { "value":"Directory.Read.All", "consentDisplayName":"Read directory data", "consentDescription":"Allows the app to read data in your organization's directory.", "isAdmin":true }, { "value":"Directory.ReadWrite.All", "consentDisplayName":"Read and write directory data", "consentDescription":"Allows the app to read and write data in your organization's directory, such as other users, groups. It does not allow the app to delete users or groups, or reset user …
=> Updates how scopes values are retrieved

package.json, src/app/views/sidebar/sample-queries/queries.ts
Investigates the reason why Microsoft Teams (beta) samples were loading samples unrelated to teams.
Fixes the issue in the local version of the queries
Fixes #249 
Changes on the api providing the samples has been done on a branch in the repository
[PR 139](https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/139)
=> fixes local samples ordering

public/index.html, src/app/views/authentication/Authentication.tsx
1. Traps the mscc object and stores it in the window variable.
2. Calls setConsent on the mscc object.
N/A
The mscc needs to be put in a window object so that it can be accessed from a React object.
N/A
=> Calls setConsent to mscc

src/app/views/query-response/snippets/Snippets.tsx
"Javascript" should be uppercase "S". Tested to make sure case sensitivity wasn't a problem with loading the language for Monaco.
Updating the snippet pivot text "Javascript" to "JavaScript".
I've updated the S in Javascript to be JavaScript in the Snippets component for the language Pivot control. Tested to make sure case sensitivity wouldn't be a problem with the monaco editor.
Load the Graph Explorer, make a sample call from the left sample queries panel. Open the "Snippets"  Pivot, and load "JavaScript" pivot.
=> Updating Mispelled JavaScript

src/app/services/actions/query-action-creator-util.ts
Running [this query](https://graph.microsoft.com/v1.0/me/calendarview?startdatetime=2020-01-27T09:01:07.519Z&enddatetime=2020-02-03T09:01:07.519Z ) in v3 worked but not in v4.
Fixes #349 
Anonymous requests sent to the proxy services should be escaped so that the API can show the data
* Spin up the app
* Run [this query](https://graph.microsoft.com/v1.0/me/calendarview?startdatetime=2020-01-27T09:01:07.519Z&enddatetime=2020-02-03T09:01:07.519Z ) in an anonymous state
* Notice the presence of results
=> Fix: Calendarview query not working

src/app/utils/sample-url-generation.ts
When typing in a url to send a request to and the url has a % character. The controls get lost. 
This PR sorts this out.
Fixes #284.
* Try adding a request to the url and enter a % sign
* Note that the controls do not get lost
=> Fix: Percentage error that causes loss of controls

src/app/views/App.tsx, src/app/views/authentication/Authentication.styles.ts, src/app/views/authentication/Authentication.tsx, src/app/views/authentication/profile/Profile.tsx, src/app/views/settings/Settings.tsx
Fixes layout problems on the sign in area when on different screens where the gear icon and the email overflow.
Fixes #352 
Fixes #332 
Below are different screenshots on screens of varying sizes
1. 
2. 
3. 
4. 
The name and the email address are wrapped with an ellipsis. The full descriptions are displayed on hover using tooltips.
The previous implementation used bespoke wrappers . This current one uses only the UI fabric and a design token to change the email to lowercase
* Resize your screen 
* Notice the gear icon does not overflow
=> Fix: sign in area issues

src/app/services/actions/query-action-creator-util.ts, src/types/enums.ts
Displays results on the response component that have a 'text/plain' in the content type header.
Fixed #377 
Exhibit A :-)
* Run this query: https://graph.microsoft.com/beta/me/calendars/$count
*  Find the results in the response component
=> Fix: Display text/plain results

src/app/services/actions/request-history-action-creators.ts, src/app/views/sidebar/Sidebar.styles.ts, src/app/views/sidebar/history/History.tsx, src/app/views/sidebar/history/history-utils.ts, src/messages/GE.json
Adds a delete button on each section (Today, Yesterday, Older) that allows a user to delete all messages in the particular section.
Fixes a previously unknown bug where the items were not permanently deleted and were repopulated on reload
Fixes #354 
Previously ran queries before this update will not be shown
* Run a query
* View it in the history section
* Click the button on the right of the Today section and notice all queries in the section are deleted
=> Feature: clear history

src/app/views/App.tsx, src/app/views/common/share.ts, src/app/views/query-response/QueryResponse.tsx
Carries over the context of the query from the try-it experience to the full GE experience.
Fixes #356 
Does not consider whether someone is logged in or not
* Open GE in try it mode
* Create a request
* click on the link in the banner
* Notice the request you ran is opened in the full experience
=> Feature: context switching

src/app/views/authentication/Authentication.tsx
Authentication text was showing when the minimise menu was hit.
=> Fix: stops showing authentication text when minimised

src/app/views/sidebar/sample-queries/SampleQueries.tsx
Added the category to the items to help filter requests in the sidebar.
We will now be able to filter the requests in a category.
Fixed #434 
N/A
* Search a category like one drive
* Notice all the onedrive items are displayed
=> Feature: Filter categories

src/telemetry/telemetry.ts
Gets the AI/AM instrumentation key from the window object.
Getting the instrumentation key is useful for automatic builds and we are building releases manually on the dev's machine.The build process will pick up the env variable and use it in the release. This has the unintended consequence of having wrong variables in the release. This PR, gets the InstrumentationKey variable from window object.
=> Get instrumentation key from window object

src/app/views/App.tsx, src/app/views/authentication/profile/Profile.tsx
Removes duplicate profiles displayed when the viewport is reduced.
Fixes #438 
* Log in to graph explorer
* Resize the browser till it gets to mobile view, 
* Notice there is only one profile picture present
=> Fix: profile misaligned

src/app/views/common/share.ts, src/app/views/query-runner/QueryInput.tsx, src/types/query-runner.ts
The url generated had spaces inside it and thus producing a faulty url.
e.g.
`https://developer.microsoft.com/en-GB/graph/graph-explorer/preview%20%20%20%20?request=users%20%20%20%20&method=GET%20%20%20%20&version=v1.0%20%20%20%20&GraphUrl=https://graph.microsoft.com%20%20%20%20&requestBody=IiI=`
=> Task: fix faulty url encoding in the url

src/app/views/query-response/QueryResponse.tsx, src/app/views/query-response/pivot-items/pivot-items.tsx, src/app/views/query-runner/request/Request.tsx, src/types/query-response.ts
On smaller screens, the view of the components (request/response) is altered.
Fixes #450 
Desktop:
Mobile:
There is currently an open issue on the [fluent ui repository](https://github.com/microsoft/fluentui/issues/4066) to help users sort this out. Hence scrolling horizontally or having a behaviour similar to an [overflowing command bar](https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar) is not feasible at the moment. 
This current implementation utilises an easier idea that the user will have interacted with the desktop version of GE before going mobile and so the icons will make things easier to find and remember.
* Minimise your screen to mobile size
* Notice the display changes to icons only
=> Fix: responsive pivot items

src/app/views/sidebar/Sidebar.styles.ts, src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #406 
"Login to run this request" changes to the already localized "Sign In to try this sample"
A key icon is not available in [the list of fabric icons](https://developer.microsoft.com/en-us/fabric#/styles/web/icons) however a Lock icon makes a lot of sense in its place
* Hover over previously mentioned elements to see the tooltips
=> Feature: Add icon on auth-required queries

src/app/views/App.tsx, src/app/views/query-runner/request/permissions/Permission.styles.ts, src/app/views/query-runner/request/permissions/Permission.tsx, src/messages/GE.json
Fixes #447 
Fixes #456 
Fixes #448 
Also:
Consent tip
Permissions table columns
* Run a query you do not have permissions for
* Notice the message
=> Feature: add permission consent tip

src/app/views/App.tsx, src/app/views/app-sections/HeaderMessaging.tsx, src/app/views/common/share.ts
When a query was passed on to try it and it lacked headers, the share link utility was unable to generate a share-able query link.
Now it does.
A similar action has happened on the master branch, This action is intended to bring it over to dev
Adds null check on headers that have been passed in through the url ti fix the shared query not populating the UI
Fixes #482
=> Fix: Share query errors

src/app/services/actions/auth-action-creators.ts, src/app/services/graph-client/msal-service.ts, src/app/views/App.tsx
Uses a workaround described in issue 1386  of [the msaljs repository](https://github.com/AzureAD/microsoft-authentication-library-for-js/).
Fixes #465 
N/A 
* Change the graphExplorerMode to TryIt
* Sign in using your preferred account
* Sign out and notice a pop up and choose the account you want to sign out from
* Reload the page
* You would need to sign out again :-)
=> Fix: try it logout

src/app/views/App.tsx, src/app/views/sidebar/Sidebar.styles.ts, src/app/views/sidebar/sample-queries/SampleQueries.tsx
Works off changes made in PR #525 by @jobala 
Reverts breakpoint to 992
Adds horizontal scrolling in the sidebar when screen size is small
Fixes #523
=> Fix: sidebar http methods

src/app/views/App.tsx, src/app/views/app-sections/AppTitle.tsx, src/app/views/authentication/Authentication.tsx, src/app/views/authentication/auth-util-components/UtilComponents.tsx, src/app/views/authentication/profile/Profile.tsx, src/app/views/query-response/pivot-items/pivot-items.tsx
Adds the setting icon into the mobile view so that a user has the chance to interact with the options available
Aligns the authentication to the left instead of centered
Extra: Fix useability inconsistency brought by showing the adaptive cards dot before a query is made. Making it appear once a query is ran shows that the response is available an adaptive card / not .
Anonymous 
Authenticated
=> Task: display settings icon mobile view

src/app/services/actions/query-action-creator-util.ts, src/app/services/actions/samples-action-creators.ts
Removes duplicate content-type headers passed in from the sample queries
* Select send an email from the sidebar
* Click run query
* Message will be sent
=> Fix: remove duplicate content type header

src/app/views/settings/Settings.tsx
Fixes #547 
* Log in to graph explorer
* Click the gear icon and select 'Select permissions'
* Click the close button and close the panel
* Click the version dropdown and notice the panel does not open
=> Fix: select permissions pop up

src/app/services/graph-client/msal-service.ts, src/app/views/common/share.ts
Adds a lower-cased redirect url to the authentication request
Removes preview from the share query link and localizes it
Partially fixes missing url in the client id error in when there is a capitalised locale as mentioned in #540 
```
https://developer.microsoft.com/es-es/graph/graph-explorer?request=me&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=dW5kZWZpbmVk
```
=> Fix: lowercase locales

src/app/services/actions/snippet-action-creator.ts
Displays snippets with search parameters.
Fixes #543 
The search parameter was omitted from the request
=> Fix: snippets generation for queries with search parameters

src/app/views/authentication/profile/Profile.tsx
Displays the login screen in mobile views
Fixes #561 
N/A
* Load GE in try it mode
* Minimise screen till it hits the mobile view
* Notice you can still see the dropdown
=> Fix: Show log-out on try it on mobile screens

src/app/views/sidebar/Sidebar.styles.ts, src/app/views/sidebar/sample-queries/SampleQueries.tsx, src/app/views/sidebar/sample-queries/tokens.ts
Makes the documentation link multiline
Changes the link colour to reflect that it is a link
Adds a placeholder token for the user-id in the presence api call
Fixes #556 
Fixes #563 
N/A
=> Fix: sample queries documentation link

src/app/services/graph-client/msal-service.ts
Currently to go a tenant in Graph Explorer, we need to create a local account in tenant. After this change a `tenant` queryString parameter can be passed and then all idtoken and access token requests will go to that tenant.
Tenant parameter can be guid or the domain name for the tenant.
**sample request** 
https://developer.microsoft.com/en-us/graph/graph-explorer?tenant=abc.onmicrosoft.com
if no tenant is specified, the request goes to common endpoint. 
MSAL.JS documentation says that default redirect uri is window.location.href but taking a look at 
[this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/d259ebab2ebc441a0eecce88381d932664c97fa1/lib/msal-browser/src/config/Configuration.ts#L65) and [this](https://github.com/AzureAD/microsoft-authentication-library- …
=> Support for tenanted endpoint in Graph explorer.

src/app/views/query-runner/QueryRunner.tsx, src/messages/GE.json, src/types/query-runner.ts
Checks if the sample body is valid before running it. Incase it is not, it provides an error "Malformed JSON body" so that someone can see that there is a syntax error that needs to be fixed
Fixes #557 
The second part in the message that contains the actual syntax error is dynamically generated and thus it's localisation is not possible.
* Log in so that you are able to send a post request
* Add an extra comma anywhere in the sample body and take note of it
* Hit enter / click run query
* Notice that an error appears saying that you have a syntax error and shows you where to find it
=> Fix: validate json

src/app/views/sidebar/history/History.tsx
User can view a query when history item is clicked
Fixes #541 
N/A
N/A
* Head over to history on the sidebar
* Click on a history item
* Notice the results appear
=> Fix: History item click action

src/app/views/query-runner/request/auth/Auth.tsx, src/index.tsx
Changes access token view with theme changes. 
Fixes #539 
Refreshes the token every token to get the latest one. 
Fixes #508 
N/A
N/A
N/A
=> Fix: access token theme change

src/app/services/actions/query-action-creators.ts
Handles errors from the sdk making the request to hang.
Fixes #555 
N/A
Errors from the sdk were not being handled. We added a default error 400 and display the actual error in the editor.
=> Fix: Post request hangs waiting for response

src/app/views/App.tsx, src/app/views/common/share.ts
Makes the graph url an optional parameter so that shared queries from documentation do not fail.
Fixes #571 
URL encodes the url to maintain all parts of the shared query
Only shares a hashed request body when a request body exists
Fixes #567 
N/A
N/A
* Run a complex query
* Click share query
* Notice that the query is encoded
=> Fix: hostname missing

src/app/utils/badge-color.ts, src/app/views/app-sections/AppTitle.tsx, src/app/views/settings/Settings.tsx, src/messages/GE.json, src/messages/GE_de-DE.json, src/messages/GE_es-ES.json, src/messages/GE_fr-FR.json, src/messages/GE_ja-JP.json, src/messages/GE_pt-BR.json, src/messages/GE_ru-RU.json, src/messages/GE_zh-CN.json
- Added tooltips to the 'minimize sidebar' and 'more actions' icons displayed to enhance keyboard navigation.
- Changed the color of the "patch" drop-down control to fit the color contrast ratio. 
=> Fix: Add tooltips and correct color contrast 

src/app/views/common/share.ts, src/app/views/query-runner/QueryInput.tsx
Running the ```create a team``` query breaks the app like so
The characters previously unsupported when hashEncoding are now supported.
* Log in
* Set to POST and run ``` https://graph.microsoft.com/beta/teams ``` adding the request body described in the [docs here](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http#example-6-create-a-team-with-a-non-standard-base-template-type)
* Notice the browser does not break 💯
=> Fix: failing create teams request

src/app/services/actions/query-action-creator-util.ts, src/app/services/actions/query-action-creators.ts, src/app/views/query-response/pivot-items/pivot-items.tsx
Fixes #634 
Creates an image url from all responses with a content type that includes images
* Log in to GE
* Run `https://graph.microsoft.com/beta/me/photo/$value`
* Notice your image is presented
=> Fix: image content types

src/app/views/query-response/QueryResponse.tsx, src/app/views/query-runner/request/permissions/PanelList.tsx, src/app/views/sidebar/sample-queries/SampleQueries.tsx, src/themes/light.ts
- Add aria-labels for screen reader support.
- Altering the secondary text color on the persona card's tooltip to fit the acceptable color contrast ratio
Fixes #495
=> Fix: Add aria-labels and correct colour contrast

src/app/views/query-runner/QueryRunner.tsx
Fixes #655 
Selecting all and pasting the url over the previous content was also working. To fully fail copy pasting the url bar has to be empty
* Clear everything on the url bar
* Copy `https://graph.microsoft.com/v1.0/me/messages`
* Paste it on the url bar
* You can choose to write it down manually
=> Fix: copy paste query address bar

src/app/utils/translate-messages.ts, src/app/views/query-response/pivot-items/pivot-items.tsx
Adds a function to be used to generate fallback texts to words which have not been translated yet.
Word here is used to mean one word or a phrase
If a **word** has no translation available in a new language but available in the default `en-US` transalation files, the `en-US` translation is displayed.
If the **word** is also not available in the `en-US` translation files, the **word** itself is displayed
Fixes #490 
1. Translation unavailable in French, available in English
-- word = Graph Toolkit
-- translation = Toolkit component
2. Translation unavailable in both French and English
-- word = Graph Toolkits
-- translation = Graph Toolkits
=> Fix: add fallback texts to placeholder text

src/telemetry/telemetry.ts
We have our instrumentation key that is unreachable by the function because the window instrumentation key is never empty.
We need to change it so that the staging environment can point to its own staging key
=> remove window instrumentation key

src/app/utils/query-url-sanitization.ts, src/tests/utils/sanitize-url.spec.tsx
This work enhances the work done by @millicentachieng in #734 to redact PII from the query url.
Assumptions made are that URL segments with identifiers are never full alphabetic strings. They will be strings with numbers / special characters.
=> task:enhance sanitise query function

src/app/views/query-runner/request/auth/Auth.styles.ts, src/app/views/query-runner/request/auth/Auth.tsx, src/messages/GE.json, src/messages/GE_fr-FR.json
Based on a [Twitter discussion](https://twitter.com/sebastienlevert/status/1324336189151891458), this would be a great feature to inspect our Access Token when using the Graph Explorer
* Open the Graph Explorer
* Connect using a Microsoft Account
* Execute `/me`
* Navigate to the Access Token pivot item
* Click on the `{ }` icon
=> Adding JWT.ms support in the Access Token view

src/app/views/authentication/Authentication.tsx, src/messages/GE.json
According to issue #753, there are 2 options(solutions) to the issue. I worked on `adding a descriptive error message after the pop-up is blocked by browser windows.` 
* Checkout to the branch
* Try logging in to Safari or chrome(Ensure that browser blocks any popups)
* Try sign in and check the error message provided after login fails
=> descriptive message after pop-up blocked in browser

src/app/views/query-response/QueryResponse.tsx, src/app/views/query-response/query-response.scss
Fixed the focus order after "Close" button by including the 'expand' and 'share' links as pivot items.
After "Close" button, focus will move to “Response preview” button instead of moving  “Share query” button.
Fixes #750 
Step 1: Open the above Graph Explorer URL in Edge browser.
Step 2: Navigate to "Close" button on Graph-Explorer page..
Step 3: Now press Tab key and Observe whether focus indicator moves to Response Preview
=> Fix: focus order

src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx
Noticed that as the request for autocomplete options is running, the results of the previous run are displayed.
If the call is running, only the spinner should show until the content is found or not.
=> Fix: stop display of options when fetching suggestions

src/modules/suggestions/suggestions.ts
The auto-complete feature is currently using the Content-Type request header.
Not only this is the wrong header to specify which format you want in return from the server, it also forces a CORS preflight which double the load per auto-complete "run" on the service, degrading the end user experience.
This pull request corrects the header usage.
Wrong:
```PowerShell
Invoke-WebRequest -Uri "https://graphexplorerapi.azurewebsites.net/openapi?url=/&style=geautocomplete&graphVersion=v1.0" `
-Headers @{
"method"="GET"
"authority"="graphexplorerapi.azurewebsites.net"
"scheme"="https"
"path"="/openapi?url=/&style=geautocomplete&graphVersion=v1.0"
"user-agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
"accept"="*/*" …
```
=> - replaces content-type header by accept to match HTTP and avoid CORS preflight

src/app/views/query-runner/request/permissions/Permission.tsx, src/app/views/query-runner/request/permissions/TabList.tsx, src/messages/GE.json, src/types/permissions.ts
- Remove 'display string' column
- Wrap information contained under 'Description' column
- Change description message dependent on whether a user has signed in or not
Fixes #653
=> Fix: modify permissions tab UI

src/app/services/actions/permissions-action-creator.ts
Sanitises the URL before sending the request to the permissions endpoint
Fixes #793 
N/A
This would take us a step towards re-activating telemetry in the devx-api 
* Add a URL with an ID/email within it
* Navigate to the modify permissions tab
* Open the network tab of the developer console to see the permission request
* Notice the id has been replaced
=> Fix: sanitize url when fetching permissions

src/app/services/actions/permissions-action-creator.ts, src/app/services/reducers/permissions-reducer.ts, src/app/views/query-runner/request/permissions/PanelList.tsx, src/app/views/query-runner/request/permissions/Permission.tsx, src/app/views/query-runner/request/permissions/TabList.tsx
When a user opens the modify permissions tab then opens the select permissions slide out, all the permissions (280 +) show in the tab as required to run the specified query.
Fixes #594 
* Open the permissions tab and the slideout at the same time
* Notice that permissions are not displayed in the tab any more if the select permissions slide out is still open
=> Fix: all permissions show as required

src/app/views/sidebar/sample-queries/SampleQueries.tsx
This ensures using keyboard navigation to run a query from the list of given sample queries is successful.
Fixes #805 
- Open the URL in Anaheim edge dev browser.
- Navigate (by Tab) to any List items say 'Get my profile' present under Expanded Getting Started button on the left side of the navigation pane and activate it using the Enter key.
- Observe the query is run.
=> Fix: Sample Queries Keyboard accessibility

src/app/views/settings/Settings.tsx, src/messages/GE.json
This PR adds a 'Report an Issue' menu option in the settings dropdown.
This option redirects a user to the new issues page on the Graph Explorer repo.
Fixes #771 
When no user is signed in 
When a user is signed in:
* Navigate to the 'More actions' icon
* Click to see 'Report an Issue' option.
* Select option to be redirected to Graph Explorer's new issues page.
=> Feature: Adds 'Report an Issue' menu option

src/app/views/app-sections/AppTitle.tsx, src/messages/GE.json
This add's the maximize sidebar aria-label to ensure accurate information is read by the screen reader.
It also ensures the tooltip message is changed from "minimize sidebar' to 'maximize sidebar' when the sidebar is minimized and vice versa when the sidebar is maximized.
Fixes #841 
_Tooltip view when sidebar is maximized_
_Tooltip view when sidebar is minimized_
=> Fix: Add 'Maximize sidebar' aria-label

src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx
Changes how the adaptive card is destroyed when unmounting to fit with typescript linting
=> fix: adaptive cards destroy

src/app/views/app-sections/TermsOfUseMessage.tsx, src/app/views/classnames.ts, src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx, src/app/views/query-response/graph-toolkit/GraphToolkit.tsx, src/app/views/query-response/queryResponse.styles.ts, src/themes/dark.ts, src/themes/high-contrast.ts, src/types/adaptivecard.ts
Fixes some link colours on GE to meet the colour-contrast ratio in dark mode.
Fixes #707 
* Open GE on your browser.
* Navigate to the 'More actions' icon and select 'Change theme'.
* Change theme to dark mode and close dialog box.
* Open dev tools and hold "Ctrl+Shift+C" to inspect elements.
* Hover above a link and observe contrast checkmark.
=> Fix: Graph Explorer link colors

src/app/services/actions/auth-action-creators.ts, src/app/services/actions/permissions-action-creator.ts, src/app/services/graph-client/msal-service.ts, src/app/views/query-runner/request/auth/Auth.tsx, src/index.tsx, src/messages/GE.json
=> Task: prevent storing access token

src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx, src/app/views/query-runner/query-input/auto-complete/SuggestionsList.tsx, src/app/views/query-runner/query-input/auto-complete/auto-complete.util.ts
Autocomplete suggestions should collapse when the autocomplete component loses focus
Fixes #721 
OnFocusOut is not supported in React hence the use of onBlur. 
* Trigger an autocomplete call
* Once the options show up click outside the component
* Notice that the suggestions close
=> fix: autocomplete-onfocusout

src/app/views/query-response/response/Response.tsx, src/app/views/query-response/response/ResponseDisplay.tsx, src/messages/GE.json
Adds a message bar with a clickable link that executes the next link so that navigation is easy
Fixes #392 
Explicitly mentioned the `@odata.nextLink` property so that users can know which property is enabling this
* Run this query `https://graph.microsoft.com/v1.0/me/messages?$select=subject`
* Notice a banner appears in the response area informing you of the ability to go to the next page
* Click the provided link and notice that the query runs the next url
=> Feature: make paging easier

src/app/views/query-response/response/ResponseDisplay.tsx
Enables syntax highlighting on $metadata queries.
Fixes #858 
Before
After
* Run `https://graph.microsoft.com/v1.0/$metadata`
* See the tags in colour
=> Fix: metadata syntax highlighting

src/app/services/actions/adaptive-cards-action-creator.ts, src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx, src/app/views/query-response/queryResponse.styles.ts, src/messages/GE.json, src/tests/services/actions/adaptive-cards-action-creator.spec.ts, src/types/adaptivecard.ts
=> Fix: Adaptive cards changes

src/app/services/actions/snippet-action-creator.ts
Fixes #876 
N/A
* Run any query
* Head over to code snippets
* Notice that the code snippet is displayed
=> Fix: snippets not available

package-lock.json, package.json, scripts/start.js
The `react-dev-utils(v11.0.4)` package needs to be downgraded as it causes breaking changes that lead to a failed compilation error
=> Fix: Undo 'react-dev-utils' package update

src/app/utils/external-link-validation.ts, src/index.tsx, src/tests/utils/external-link-validation.spec.ts
The devx-api query parameter can be overridden with javascript and this is a security risk due to XSS attacks
=> Fix: javascript injection

azure-pipelines.yml, src/app/views/settings/Settings.tsx
Changes the current 'more actions' icon from the settings gear to the ellipsis icon to indicate 'more'.
Fixes #882 
_before_
_update_
=> Feature: Enhance 'More actions' icon appearance

src/app/views/App.tsx
Problem: Graph explorer crashes if HTTP method is missing in query params
Fix: Default HTTP method to 'GET' if missing or invalid
Example link: 
https://developer.microsoft.com/en-us/graph/graph-explorer?request=me&version=v1.0
=> Set GET as default HTTP method if method specified in query params is invalid or missing 

package.json, src/app/views/App.tsx
=> Merge v4.6.1

.github/workflows/azure-static-web-apps-jolly-sand-0ac78c710.yml, src/app/utils/string-operations.ts, src/app/views/settings/Settings.tsx, src/telemetry/ITelemetry.ts, src/telemetry/telemetry.ts
We have been collecting telemetry for the themes that our users are opting to use. I have noticed that some them names are captured in other languages depending on the users locale.
I am using the `selectedTheme.key` instead which is lower case and hyphenated. I'm replacing the hyphen with a space and capitalizing the first letter. e.g. `high-contrast` => `High contrast`
=> Task/telemetry capture English theme names only

src/telemetry/telemetry.ts
Include deployed version of GE in all telemetry data captured.
1. Open developer tools
2. Go to Network tab
3. Trace `track` calls 
4. Application version should be captured with the tags property of response
=> Capture deployed version of GE for all telemetry data collected

src/types/query-runner.ts
Fixes #843 
The try-it experience fails to load if the concept page does not pass in a permission property. Making it optional should prevent the failure.
=> Fix: Concept try-it button

src/app/views/query-runner/query-input/QueryInput.tsx, src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx, src/messages/GE.json
Fixes #643
* Delete the sample query
* Attempt to run the query
* Notice the button is disabled and a message is presented
=> Fix: prevent running empty requests

.github/workflows/publish-release.yml, src/types/query-runner.ts
Automate message sending. Can be reused by multiple teams to send notifications to their deployment channels.
Closes #959 
Sample Microsoft teams notification created in a channel with the change log and a link to the release
Sample Outlook email notification created in a group. Members of the group also get notified in their inbox
- Add an incoming webhook connector to the chosen Microsoft Teams channel 
- Place the webhook URL into the repository secrets under **TEAMS_WEBHOOK_URL**
- Create a group and add all expected recipients
- Add an incoming webhook connector in the group settings
- Place the webhook URL into the repository secrets under **OUTLOOK_WEBHOOK_URL**
=> Feature: send notification when release is created

src/app/views/authentication/auth-util-components/UtilComponents.tsx, src/app/views/query-runner/request/auth/Auth.tsx, src/app/views/query-runner/request/permissions/Permission.tsx, src/app/views/sidebar/history/History.tsx
This PR fixes multiple accessibility issues present on GE: 
Step 1: Open the above URL in Edge browser.
Step 2: Open Narrator using 'Win + Ctrl+ Enter' key.
Step 3: Navigate to **Sign in to graph explorer** button using the Tab key.
Step 4: Observe the Fix.
Step 5: Navigate to the **History** tab item for the page by the Tab and Right Arrow key and activate it.
Step 6: Navigate to the **Expand collapse group button** by Tab key and activate it.
Step 7: Observe the narration here
Step 8: Navigate to the **Modified permission (Preview)** button by tab key and activate it by using the Enter key.
Step 9: Observe 'Admin Consent required' column fix
=> Fix: Accessibility bugs - June

src/app/services/actions/profile-action-creators.ts
Closes #975 
The browser does not get a user's profile each time because of the default browser cache settings hence why the image is not fetched afresh from the service.
* Log in to GE with account A with a profile image
* Logout of account A
* Log in to GE with account B with a different profile image
* Notice the different profile picture is loaded
=> FIx: Clear the user's profile on sign out

src/app/services/actions/permissions-action-creator.ts, src/app/views/query-runner/request/permissions/Permission.tsx, src/types/permissions.ts, src/types/root.ts
Closes #994 
Scenario:
- A user opens a query's modify permission page
- The user opens the permissions panel 
- The user closes the permissions panel and is now back on the modify permissions page
The fix now repopulates the modify permissions screen with the permissions (if any) of the query URL that is in the URL bar
Follow this link: [https://jolly-sand-0ac78c710-999.centralus.azurestaticapps.net/](https://jolly-sand-0ac78c710-999.centralus.azurestaticapps.net)
* Log in to GE
* Select `my mail` and take note of the permissions displayed
* Head over to the more actions icon and open the Select Permissions panel
* Close the Select Permissions panel
* Notice the original permissions belonging …
=> Fix: repopulate modify permissions when panel closed

src/app/services/actions/query-action-creator-util.ts
Closes #979 
Double encodes the `#` characters present in the url
N/A
N/A
* Run `GET https://graph.microsoft.com/v1.0/users/Nic#Von@chambele.onmicrosoft.com`
* Observe `message": "Request with $search query parameter only works through MSGraph with a special request header: 'ConsistencyLevel: eventual'",`
* Add the 'ConsistencyLevel: eventual' headers to the request
* Run the query again and notice it does not fail
* Run `GET https://graph.microsoft.com/v1.0/users/Nic#Von@chambele.onmicrosoft.com`
* The response will now indicate it can't find the user Nic#Von@chambele.onmicrosoft.com
* Look in Fiddler and observe that the full URL is sent.
=> Fix: url truncation

src/app/services/actions/query-action-creator-util.ts, src/app/utils/query-url-sanitization.ts, src/app/views/common/share.ts
Refines the work done in #1012 to:
- remove an extra path from sandbox URL brought in from a merge where the path was added
- prevents truncation when sharing a query with a #
=> Task: refine url truncation

src/app/views/common/monaco/Monaco.tsx
Fixes response truncation observed when a user runs a query.
Fixes #957 
_before fix:_
_after fix:_
If You get a 404-Bad request. Add 'ConsistencyLevel: eventual in the **Request header** tab
* Load app.
* Run 
`GET https://graph.microsoft.com/v1.0/servicePrincipals$count=true&$search="displayName:teams"&$select=id,displayName`.
* Observe **@odata.id** field in the Response Preview.
* Observe url is wrapped.
=> Fix: Response Preview truncation

src/app/views/sidebar/sample-queries/tokens.ts
The tokens added in this PR are used in our soon-to-be proposed sample queries for Teams chats. This PR will need to be merged before we can merge any sample queries into the https://github.com/microsoftgraph/microsoft-graph-devx-content repository; Otherwise, the sample queries will not work because they cannot populate the required tokens in sandbox mode.
The `chat-id` used is the first chat returned when using the `GET https://graph.microsoft.com/beta/me/chats/` query in sandbox mode, and the `membership-id` used is the first chat member id returned when using the `GET https://graph.microsoft.com/beta/me/chats/{chat-id}/members/` query in sandbox mode.
All of the newly committed IDs have been tested on `localhost`.
=> Add chat-id & membership-id

src/app/utils/status-message.ts
**Issue:**
Sample queries with tips that have clickable query links will populate the query runner with a trailing "." if the . was at the end of the link. This is due to the way that the links are parsed.
**To test:**
All of the "Excel" sample queries, and more, have periods at the end of the tip message that contain clickable query links. To test this change, click one of these links in the tips that end in a "." and ensure that:
1. The link highlighting should not extend to the .
2. The link placed in the query runner should not contain the .
https://user-images.githubusercontent.com/49354780/126227792-e5d61980-1257-4f28-8c29-718e3edc327d.mp4
If the following tests pass, the bug is fixed, as demonstrated in the gif 😊 
[AD#39035](https://dev.azure.com/microsoftgarage/Intern%20GitHub/_spr …
=> Fix query link parsing with trailing '.'

src/app/views/query-runner/request/headers/RequestHeaders.tsx, src/app/views/query-runner/request/permissions/TabList.tsx, src/app/views/sidebar/history/History.tsx, src/app/views/sidebar/sample-queries/SampleQueries.tsx
The existing DetailsList scrollbars are the default Edge light mode scrollbars that appear when there is overflow (see right of screenshot below), and they are jarring to the user especially if they are on dark mode. 
https://dev.azure.com/microsoftgarage/Intern%20GitHub/_sprints/taskboard/GI21%20-%20Graph%20Explorer/Intern%20GitHub/Y21-S/06?workitem=38891
The changes in this PR will hide the scrollbars until the user hovers over a DetailsList with overflow, then the scrollbars will appear. 
https://gyazo.com/ceaaa8648891cd6e7b672bac68b775d8
Four scrollbars have been changed: 
History list, Sample Queries list, Permissions (panel tab) list, and Request Headers (panel tab) list. 
* Front-end, test the four lists above (and shown in the demo recording). 
* Cross browser testing: developed …
=> Feature/DetailsList scrollbars only appear onHover

src/app/views/query-response/pivot-items/pivot-items.tsx, src/app/views/query-runner/request/auth/Auth.tsx
I had a brief chat with an engineer who was on the Fluent UI team who confirmed that aria labels should always be localized, and I noticed some aria labels not localized in the codebase. 
https://dev.azure.com/microsoftgarage/Intern%20GitHub/_sprints/taskboard/GI21%20-%20Graph%20Explorer/Intern%20GitHub/Y21-S/08?workitem=39309
=> Add translated aria labels

src/tests/utils/proxy-url.spec.ts
Due to changing the Proxy API endpoint, the test previously targeting the original endpoint is failing. This PR removes the test as it is no longer necessary
=> Task: remove sandbox api test

src/app/views/sidebar/Sidebar.styles.ts, src/app/views/sidebar/sample-queries/SampleQueries.tsx
Enhances #1023 to use CSS instead of javascript functions to show the hover
=> Fix: change hover scroll behaviour

src/telemetry/filters.ts
Capture GE mode for all telemetry items sent to Application Insights.
This is to help us properly distinguish between Try It and main GE telemetry.
Load Graph Explorer and click on the Run query button while on the network tab of developer tools.
=> Capture GE mode for all telemetry items

src/telemetry/filters.ts
We are missing some data by updating some properties of App Insights telemetry item properties. The aim was to ensure that we capture only data that is necessary but this has caused App Insights to send very minimal data thus missing some error metrics.
Simulate error on Graph Explorer. Look at the data sent to the Azure Portal.
=> Update how we are sanitizing track trace to include more info

src/app/services/graph-constants.ts, src/app/utils/graph-toolkit-lookup.ts, src/telemetry/filters.ts
Capture telemetry for when a user clicks on the graph toolkit example link.
- Open developer tools on browser and go to network tab
- Run query as an anonymous user
- Check to see if telemetry data has been sent to Application Insights
=> Capture telemetry for graph toolkit example link

src/app/views/query-response/QueryResponse.tsx
Solves #1119 
Change theme to dark theme
Click on 'Share'
The share url is visible
=> makes query color in the text area visible in dark mode

src/app/views/App.tsx, src/app/views/query-runner/util/iframe-message-parser.spec.ts, src/app/views/query-runner/util/iframe-message-parser.ts
Fixes #1021 
Fixes #998 
"Try it" code in Microsoft Docs doesn't escape the " ' " character #998
GE try-it truncating URL #1021
* Go TO: https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-14820&tabs=http
* Scroll down to Example 5
* Click on try-it
* Notice that the whole URL is copied in without truncation
=> Fix: try it interaction

src/app/views/app-sections/ResponseMessages.tsx
Fixes #1178 
Previously the url was decoded to make it more readable. Now it doesn't decode ensuring the app runs
* Run this query `https://graph.microsoft.com/v1.0/me/messages?$select=subject`
* Notice a banner appears in the response area informing you of the ability to go to the next page
* Click the provided link and notice that the query runs the next url
=> Fix: failing nextlink call

src/app/views/query-response/QueryResponse.tsx, src/app/views/query-response/query-response.scss, src/app/views/query-runner/request/Request.tsx
Fixes request and response heights on try-it experience and nps. 
Assigning classname dynamically to the response pivot was breaking experiences that rely on the classname being static.
The responsiveness that relied on the dynamic classname has been moved to the scss file as a media query.
Set graphexplorermode to Mode.TryIt: The response height is maintained above a set minimum.
Launch nps feedback through the button: The pop-up does not push the request height to the top
=> fix: request and response height on try-it

src/app/views/sidebar/history/History.tsx
The 'Older' and 'Yesterday' group collapse when the mouse focus is moved elsewhere after a user runs a query from either of these groups.
This fix ensures the focus remains on the query selected even if the mouse focus moves elsewhere.
Fixes #1156 
* Load Graph Explorer
* Navigate to the History Tab 
* Select a query from the "Yesterday' or 'Older' group
* Move mouse focus to anywhere else on the page
* Notice the group doesn't collapse, and highlight remains on the selected query.
=> Fix: Remove hover functions on history tab

src/app/services/actions/snippet-action-creator.ts, src/app/views/query-response/snippets/Snippets.tsx
Fixes linting errors causing pipeline to fail
=> Fix: Linting errors in snippets

src/app/services/actions/query-action-creators.ts, src/app/utils/status-message.ts, src/tests/utils/url-to-html.spec.ts
Solves #1078 
On production, the status message is missing
This PR adds the status message to the response if it's unavailable
Start Graph Explorer
Click on any sample queries when you are **not signed in.** You should see the status messages for all GET sample queries
=> Task: add status message for anonymous queries

src/app/views/query-runner/request/Request.tsx
Solves #1272 
Resize the request section to the top. It stretches to the top
=> fix: restores ability to stretch request section

.prettierrc, src/app/utils/query-parameter-sanitization.ts
Selecting `$orderby` query option from autocomplete dropdown should not cause GE to crash.
* Try selecting `$orderby` query option from autocomplete dropdown in [production](https://developer.microsoft.com/en-us/graph/graph-explorer) and note the crash
* Do the same with changes in this PR, crash should not happen
=> Fix selecting  query option in autocomplete dropdown causing crash

src/app/views/query-response/pivot-items/pivot-items.tsx
Returns the blue dot when supported queries are ran
=> Fix: return blue dots on supported tabs

src/app/utils/sample-url-generation.ts, src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx, src/messages/GE.json, src/tests/utils/sample-url-generation.spec.tsx
Adds a validation message when whitespace is added anywhere before a query parameter in the query Url
Fixes #788 
Case where a space is included in the wrong place
Case where there's a space after a query parameter
* Load Graph Explorer
* In the query input field, add a space at random places within the query
* Observe error message
* Now try run a query that has parameters that have spaces, such as `https://graph.microsoft.com/v1.0/me/contacts?$filter=emailAddresses/any(a:a/address eq 'garth@contoso.com'`
* Observe error message isn't displayed
=> Fix: Add validation for whitespaces included in a query Url

src/app/services/actions/query-action-creators.ts
Solves #1363 
Click on any sample query
Go to history tab
Click on the query in the history tab
Notice that the status message is displayed on the status bar
=> add status message to history item

src/app/views/common/copy/CopyButton.tsx, src/app/views/query-response/QueryResponse.tsx
Fixes #1370 
- This fix enables focus to remain on the copy button once selected (i.e for all copy buttons: Access token, code snippets, Adaptive Cards-Json Schema, and Share dialog)
- also fixes an issue where clicking on copy in the "share" dialog would also close the dialog 
- It also add's a border on the textarea in the share dialog, which previously looked bare in light mode.
1. Open URL in Edge browser.
2. Login with valid credential.
3. Navigate to the 'Action token' button using tab key and activate it using enter key.
4. Now, navigate to the 'Copy access token' icon button using tab key and activate it.
6. Observe if focus remains on the button
=> Fix: Enable focus to remain on copy button when clicked

src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #1369 
Adding an aria-label enables screen readers to read the different query samples.
* Open GE
* Turn On Narrator using 'Ctrl+Win+Enter'.
* Navigate to the 'Get myprofile' button using down arrow key in scan mode (To turn on/off:  capslock + space)
=> Fix: Add aria-label for items in the sample queries tab

src/app/views/query-runner/query-input/auto-complete/suffix/SuffixRenderer.tsx, src/messages/GE.json
Fixes #1372 
Adds focus on the 'i' icon on the query input textfield
* Open Graph Explorer
*  Using tab key navigate to the 'i' button present beside query edit field.
* Observe if keyboard focus is going on it.
=> Fix: Query input 'i' icon focus

src/app/services/actions/permissions-action-creator.ts, src/app/services/actions/profile-action-creators.ts, src/types/profile.ts
Closes #1327 
* Sign in to Graph Explorer
* Use a different account to  consent to permissions
* Notice the user profile including photo is updated without the need to reload the page
=> Update user profile information if a different account has been used to consent to permissions

src/app/views/sidebar/history/History.tsx
Solves  #1561 
Open Graph Explorer
Click on history tab
Notice the chevron icon is correctly positioned
=> Adjust position of chevron icon on history items' headers

src/app/views/app-sections/StatusMessages.tsx, src/types/status.ts
Fixes how the Tip message is displayed on running sample queries
fixes #1570 
Currently the Tip messages displays the 'tip' word at the end and the links aren't highlighted
After fix, the tip message format is restored
* Load GE
* Sign in
* In the _**Sample Queries**_ tab, expand the **_Applications_** group and select any GET query
* Observe Tip message
=> Fix: Update Tip message format

src/app/views/query-runner/request/permissions/PanelList.tsx, src/app/views/query-runner/request/permissions/TabList.tsx
Fixes #1577 
Modify permissions and permissions panel work as expected
Sign in to Graph Explorer
Click on Modify Permissions tab
Notice that permissions are displayed as they should be
=> Fix: Validate permissions before any operations

src/app/services/reducers/dimensions-reducers.ts, src/app/views/App.styles.ts, src/app/views/App.tsx, src/app/views/common/monaco/monaco.scss, src/app/views/query-response/QueryResponse.tsx, src/app/views/query-runner/request/Request.tsx
Fixes #1414 
Rationale behind setting heights to 100%
- When moving the app between different screens, it does not extend to fill the full height of the browser window. Forcing a height of 100% ensures that the app fits the full screen regardless of the height of the browser window. 
Resize the request section upwards. Notice that the response section does not extend beyond the bounds of the app
Move the app between different screens. Notice that it resizes to fit into the new screen. The request and response sections resize to fit the new screen.
Zoom the app until it changes to a mobile view. Zoom back to full-screen view. Notice that the sidebar color is consistent throughout the length of the sidebar.
=> Fix: Makes app height responsive on all browsers

src/app/views/App.tsx
Fixes #1635 
The flex direction on try-it experience should be a column. The content area is displayed as a mobile view. 
Add a 'theme' parameter to the url like so: 'https://jolly-sand-0ac78c710-1636.centralus.azurestaticapps.net/?theme=dark'
Notice the fix
=> Fix: Change flex direction to column when on try-it experience

src/app/views/query-runner/request/permissions/TabList.tsx
Fixes #1640 
Ensure there's a query in the query text box
Click on Modify Permissions tab
=> Fix: Display permissions on Modify Permissions tab

src/app/views/App.styles.ts, src/app/views/App.tsx, src/app/views/app-sections/FeedbackButton.tsx, src/app/views/main-header/MainHeader.styles.ts, src/app/views/main-header/MainHeader.tsx
Fixes layout on new UI
Resize the UI on different screens. Notice that responsiveness is consistent, and all sections are well positioned
=> Task: page layout

src/app/views/sidebar/Sidebar.styles.ts
Makes sidebar content cover more space that is now available
Previously:
Currently:
Run it locally
Notice that the samples, resources and history items cover the available space
=> Task: Extend sidebar content space

src/app/views/settings/Settings.tsx
- Removes scrollbar from settings menu
- Centers the GitHub logo
Click on the settings icon
A settings menu appears. Notice that the scrollbar is no longer there
=> Remove scrollbar from menu

src/app/views/authentication/Authentication.styles.ts, src/app/views/authentication/Authentication.tsx, src/app/views/authentication/profile/Profile.styles.ts, src/app/views/authentication/profile/Profile.tsx, src/app/views/main-header/MainHeader.styles.ts, src/app/views/main-header/MainHeader.tsx
Aligns tenant name, settings and authentication items
Run it locally
Notice that all header items are well aligned
Click on the persona icon to sign in. Notice that the spinner and the signing in text are all aligned
=> Fix: align right header items

src/app/services/actions/query-action-creator-util.ts
Fixes #1725 
If a reports  endpoint throws an exception, it's most likely a CORS error. 
* Run the query `https://graph.microsoft.com/v1.0/reports/getMailboxUsageDetail(period='D7')`
* CORS information should be displayed in the response area
=> Show CORS information for reports that result in an exception

src/app/views/main-header/ThemeSetting.tsx
Keeps theme chooser dialog options within one line
Solves #1738 
Click on the theme toggle button at the top right
Notice the chooser dialog has the options in one line
=> Keeps theme chooser options within one line

src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/ResourceLink.tsx
Fixes isolation issue on Resource Explorer, where clicking 'Isolate' does not show the isolated resources
Solves #1743 
Click on the resources tab
Click on the more actions button on any resource item
Now click Isolate
Notice that the isolated resource items are available
=> Show isolated resources

src/app/views/authentication/Authentication.tsx, src/app/views/authentication/auth-util-components/UtilComponents.tsx, src/app/views/authentication/profile/Profile.styles.ts, src/app/views/authentication/profile/Profile.tsx
Hovering over profile icon reveals a consistent profile size
Click on the sign-in profile
Sign in with your account
Hover over the profile, help and settings icons
Notice that the size of the icons is the same
=> Fix: Auth icon size

src/app/views/authentication/auth-util-components/ProfileButton.styles.ts, src/app/views/authentication/auth-util-components/ProfileButton.tsx, src/app/views/authentication/auth-util-components/UtilComponents.styles.ts, src/app/views/authentication/auth-util-components/UtilComponents.tsx, src/app/views/authentication/auth-util-components/index.tsx, src/app/views/authentication/profile/Profile.styles.ts, src/app/views/authentication/profile/Profile.tsx, src/app/views/main-header/MainHeader.styles.ts, src/app/views/main-header/MainHeader.tsx, src/app/views/main-header/settings/Settings.tsx
Restores styling on the permissions panel:
Fixes alignment issue on the Graph explorer label on mobile screen
Run it locally
Resize screen from mobile to full screen view. Notice fix
=> Fix: Restore permissions styles

src/app/views/App.tsx
Limits sidebar resizing so that the sidebar buttons do not overlap the sidebar on hover as shown: 
Resize the sidebar until the sidebar items disappear and you have sidebar buttons only. 
Notice that the resizing does not go beyond a certain point.
=> Task: Limit sidebar resize

src/tests/accessibility/accessibility.spec.ts
Now that the pivot items have an overflow behavior aria label, we can remove the rule that excludes button-names on the accessibility checks.
=> Remove button-name from accessibility exclusion

src/app/views/query-runner/query-input/share-query/ShareQuery.tsx
Closes #1838 
Notice that the shared query has the {user-id} encoded
Add a url with any PII on the query textbox
Click on the share query button
Notice that the query in the share-query dialog does not contain the PII
=> Sanitize sample url before sharing

src/app/views/sidebar/history/history-utils.spec.ts
Closes #689 
Open your terminal and run 'npm run test'
Notice that all tests pass.
Open history-utils.spec.ts file
On the last test 'should return unexpired history items', change the date on createdAt to 'new Date().toString()'
Open your terminal and run 'npm run test'
Notice that the test fails because the history item is valid
=> Add test for history item expiry

.github/workflows/cut-release.yml
The PR body is unnecessarily verbose when we are making our releases. 
This will reduce the content to what's been committed since the last tag
=> Chore: reduce PR body content

src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #1930 
Checkout this branch and run it locally
Check the method names on the sample queries tab
=> Fix: Center method names on sample queries

src/app/views/authentication/Authentication.tsx, src/app/views/main-header/Help.tsx, src/app/views/main-header/settings/Settings.tsx, src/telemetry/component-names.ts
Fixes #1943 
This PR adds telemetry to measure clicks on the Settings button, Help button, Sign in button and the Sign in with a different account button.
=> Task: Add missing header telemetry

src/app/views/query-response/QueryResponse.tsx, src/app/views/query-response/pivot-items/pivot-items.tsx, src/app/views/query-runner/request/Request.tsx
Fixes #1861 
- Open test link.
- Hover over Request Body and other pivot controls
- Hover over Response Preview and other pivot controls  
- Observe tooltips are no longer present
=> Fix: Remove pivot tooltips

src/app/utils/generate-groups.ts
Fixes #1862 
- Turn on Narrator using ‘Win + Ctrl + Enter’ key.
- Open Graph Explorer in Edge browser.
- Navigate the left navigation pane via down arrow key,
- Observe narrator no longer mentions the expand/collapse state
=> Fix: Remove expand/collapse string

src/telemetry/component-names.ts
Adds telemetry needed to capture clicks on the PHP docs present in the Code snippets tab
=> Task: Add PHP docs link telemetry

config/webpack.config.js, src/app/services/actions/snippet-action-creator.ts, src/app/views/query-response/snippets/Snippets.tsx
This reverts commit bda63a7ce35ccc93c2b57c7b3918d4e3abd0a36c.
Reverting this since this isn't part of the July milestone
=> Revert "Feature: Add PHP Snippets tab. (#1923)"

src/app/views/query-runner/query-input/share-query/ShareQuery.tsx
Fixes #1991 #1986 
Page no longer results in 404 when queries with 
Type a query with query parameters on the query textbox
Click on the share button and copy the generated share url
Paste the url in a new tab
Notice that it no longer results in a 404
=> Disable sanitization of query url when sharing query

src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx, src/app/views/query-response/graph-toolkit/GraphToolkit.tsx, src/app/views/query-response/queryResponse.styles.ts
Closes #2019 
- Checkout to fix/top-left-align-text and run locally
- Copy this URL (https://graph.microsoft.com/v1.0/applications?$count=true) in the query textbox
- Run the query
- Click on toolkit component and observe fix
- Click on adaptive cards and observe fix
=> Fix: Text-alignment on the text in query response tabs

src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx, src/app/views/query-runner/query-input/auto-complete/auto-complete.util.ts
Fixes #2017 
Autocomplete options do not appear for /me unless when typing on the query textbox
Click on 'my profile (beta)' sample
Now click on 'my profile' sample
Notice that the suggestions do not appear for these cases
=> Fix: Autoloading suggestions on  /me

src/app/views/sidebar/sample-queries/queries.ts
- Closes #2036 
- This PR updates the set of cached queries in queries.ts which are essential when DevX API fails to return the sample queries.
* Checkout to fix/update-cached-queries
* Configure your browser to slow network or low connectivity
* Load graph explorer and observe fix
=> Fix: Update the cached queries in queries.ts

src/app/views/app-sections/StatusMessages.tsx, src/app/views/sidebar/sample-queries/SampleQueries.tsx
Closes #2035 
Click on any sample query
Notice that the query is populated on the query runner area and not run
Repeat these steps for the Resources
=> Fix: Disable running queries on clicking samples

src/app/views/app-sections/StatusMessages.tsx, src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #2046 
Sign in with any account
Click on any sample that has a tip e.g., 'delete an application'
Click on the query on the status message
Notice that the method is updated
=> Fix: Populate method with GET for queries selected from tips

src/app/views/common/monaco/Monaco.tsx, src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx
Fix #2020 
* Checkout branch and load GE
* Run the v1.0/me query
* Navigate to Adaptive Cards, JSON Schema tab
* Observe yellow line is no longer there
=> Fix: Schema validation for Adaptive cards 

src/app/views/sidebar/sample-queries/SampleQueries.tsx
Closes #2100 
Click on any sample group and select any item
Notice that the sample group does not collapse
=> Fix: Prevent sample groups from collapsing

src/app/views/common/monaco/Monaco.tsx, src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx, src/app/views/query-response/query-response.scss
Fixes #553 
By double-clicking on the ID field, we get the whole ID
Be default, word separators string on the Monaco editor is: '`~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?. We only need " as a word separator. This makes it possible to select all fields within ""
Run a query like /v1.0/me
Double click on the ID field
Notice that the whole ID field is selected
=> Fix: Update wordSeparators in Monaco

SECURITY.md, package-lock.json, package.json, src/app/views/App.tsx, src/app/views/app-sections/TermsOfUseMessage.tsx, src/app/views/main-header/Help.tsx, src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx, src/app/views/sidebar/sample-queries/SampleQueries.tsx, src/app/views/sidebar/sample-queries/queries.ts
fixes #2147 
With the new Microsoft Learn Platform rebrand, the link changes from `docs.microsoft` to `learn.microsoft`.
This, therefore, makes it necessary to update the doc links on GE to prevent redirection failures in the future and fix the issue above.
=> Task: Update doc.microsoft links to learn.microsoft

src/app/utils/query-parameter-sanitization.ts, src/app/utils/query-url-sanitization.ts
=> Fix: display suggestions for placeholder segments

src/app/services/actions/auth-action-creators.spec.ts, src/app/services/actions/auth-action-creators.ts, src/app/services/reducers/auth-reducers.ts
Fixes #2161 
Sign in to the app 
Click on Modify Permissions tab
Click on the Profile component and sign out
Sign in again ensuring that the Modify Permissions tab is still open
Notice that the app no longer crashes
=> Fix: Pass empty string to signOutSuccess when signing out

src/app/views/query-runner/request/permissions/PanelList.tsx
Fixes #2166, fixes #2168
Where a searched permission doesn't exist, the "We did not find any permissions." message is displayed. Also, there are no longer any empty groups.
Also fixes an issue with the tenant info and settings icon getting displaced
* Sign in
* Navigate to the Profile icon
* Click on "Consent to Permissions"
* In the search box, type out a permission that doesn't exist
* Observe the fix
=> Fix: Permission search results

src/app/views/query-runner/query-input/auto-complete/suffix/HintList.tsx, src/app/views/query-runner/query-input/auto-complete/suffix/SuffixRenderer.tsx, src/telemetry/component-names.ts
Closes #2186
The component identifier used to track telemetry for the more info button documentation link was similar to the sidebar documentation link. This PR aims to distinguish each for easier identification later.
=> Task: more-info telemetry capture

.github/CODEOWNERS, .github/policies/jit.yml
Enables JIT admin access to repo using https://repos.opensource.microsoft.com/orgs/microsoftgraph/repos/microsoft-graph-explorer-v4. Removes the need to manage CODEOWNERS via commits, just update the team.
=> Task: Move codeowners to team, add JIT admin access cfig

src/app/utils/resources/resources-filter.ts, src/modules/suggestions/suggestions.ts
Fixes #2257 
The matching has been failing because the urls in resource explorer do not match with how the URL sanitization is done in Graph Explorer.
For example `/users/abcd-efgh` will be sanitised to `/users/{users-id}` while resource explorer comes with the content as `/users/{user-id}`.
We have been using exact matches for strings to get the next resources available instead of checking whether they follow the same pattern.
=> Fix: pattern matching urls

src/app/utils/device-characteristics-telemetry.ts, src/app/views/query-runner/request/Request.tsx, src/app/views/query-runner/request/permissions/PanelList.tsx, src/app/views/query-runner/request/permissions/Permission.styles.ts, src/app/views/query-runner/request/permissions/Permission.tsx, src/app/views/query-runner/request/permissions/util.ts
Closes #2260 
The request resize handle has a bug that has been fixed on this PR.
Click on the Modify Permissions tab
Notice the consistent styling
=> Fix: Modify permissions styling

src/modules/validation/abnf.spec.ts, src/modules/validation/abnf.ts
Fixes #2265 
Adding a % in a random location fails the decodeUrl function in the abnf validator.
=> Fix: % symbol crash

package-lock.json, package.json, src/app/views/query-response/graph-toolkit/GraphToolkit.tsx, src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #2363 
I was unable to reproduce the issue, the deprecated label might be what's causing it.
* Run accessibility insights
* observe fix
=> Fix: Update deprecated aria-label

package.json, src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/panels/postman.util.spec.ts, src/app/views/sidebar/resource-explorer/resource-explorer.utils.spec.ts
Closes #2356 
* Checkout to this branch.
* Load local instance of GE.
* Navigate to the Resources Explorer tab
* Toggle the **Switch to beta** toggle button
* Observe groups under the **admin** group
=> Fix: Display beta resources subgroups for admin group

src/app/views/query-runner/query-input/QueryInput.tsx, src/app/views/query-runner/query-input/auto-complete/auto-complete.util.ts, src/messages/GE.json
Closes #2359 
The ABNF validator only validates URLs that have the http/https protocol appended. We therefore need extra validation when the abnf validator is not returning an error. 
Backspace on the query URL until there's only http left
See fix
=> Fix: Inform user if URL is incomplete

public/index.html, src/app/views/App.tsx, src/index.tsx
Closes #2402 
React rendering in React18 is a bit different with the other versions. From the documentation, `root.render` clears all HTML before rendering the main component https://beta.reactjs.org/reference/react-dom/client/createRoot#:~:text=The%20first%20time%20you%20call%20root.render%2C%20React%20will%20clear%20all%20the%20existing%20HTML%20content%20inside%20the%20React%20root%20before%20rendering%20the%20React%20component%20into%20it.
This is why the screen blanks before the main component is rendered. 
Within the componentDidMount method, we are sure that the main component is already in the DOM, so we can safely remove the spinners
Load this branch and run GE
Notice that the transition between the loading …
=> Fix: Screen blanking on render

src/app/views/query-response/QueryResponse.tsx
Closes #2420
The issue was due to React 17 upgrade, this affected how events are controlled and fluentUI mentions this in the docs.
Ref: https://developer.microsoft.com/en-us/fluentui#/controls/web/layer#ILayerProps
* Checkout branch
* Run GET my profile query
* Select Expand Tab
* Try to select/highlight the code on the tab
=> Fix: Enable code selection in Expand view

src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #2460 : Letters that are supposed to suspend ('g', 'p', 'y') are getting cut off. 
Before:
After
Added a padding to the bottom of the title
=> Fix: Suspending letters get cut off

src/app/views/query-runner/request/permissions/TabList.tsx, src/tests/ui/anonymous-experiences/request.spec.ts, src/tests/ui/authenticated-experiences/authenticated-experiences.spec.ts
When peermissions are not found on the permissions tab, the correct message is not displayed
Type a query like https://graph.microsoft.com/v1.0/meeeeees
Click on the Modify Permissions tab
Notice fix
=> Fix: Missing return statement

src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/ResourceLink.tsx, src/app/views/sidebar/resource-explorer/resourcelink.utils.ts, src/types/resources.ts
Closes #2405 
Changes the icon when item already exists in a collection
=> Task: Show feedback - add to collections

src/app/middleware/localStorageMiddleware.ts, src/app/services/reducers/collections-reducer.ts
Guarantees that:
- unique paths are added to a collection
- paths added to a collection are always available on reload
=> Chore: append unique paths to collection

src/app/views/sidebar/resource-explorer/resourcelink.utils.spec.ts, src/app/views/sidebar/resource-explorer/resourcelink.utils.ts
Nodes that are ids e.g. {agreementAcceptance-id} were not showing the correct status when all their children have been added to a collection. This confirms that they are captured correctly
=> Fix: collection status for nodes with IDs

src/app/middleware/localStorageMiddleware.ts, src/app/services/reducers/collections-reducer.spec.ts, src/app/services/reducers/collections-reducer.ts, src/app/services/reducers/collections-reducer.util.ts
The current check doesn't guarantee that items added to the collection are unique. 
This PR also guarantees that the logic is repeated when updating the underlying collection
=> Chore: ensure unique paths

.github/CODEOWNERS
codeowners didn't have the correct name specification.
=> fix:  CODEOWNERS file

.github/fabricbot.json
This PR solves a nit pick. When users leave comments on issues that are responded to by the bot, they are not mentioned. Their usernames are just commented. Adding an '@' infront of the username would make sure that Github recognises it as a mention
=> Chore: Mention user in external issues

src/app/views/app-sections/StatusMessages.tsx
Fixes #2616
* Spin up this branch locally
* Expand 'Excel' in the sample queries
* Click on 'GET worksheets in a workbook'
* Tip is displayed reading "Tip - This query requires a driveItem id…"
* Click the sample query to copy it to the query textbox
* Notice the query is added without the trailing dot
=> Fix: remove all trailing dots

package-lock.json, package.json, src/app/views/sidebar/resource-explorer/ResourceLink.tsx
Some nodes like chats in the Resource Explorer, which have documentation links, didn't have their links showing. This changes now with a difference in implementation to make it similar to the Query bar.
Before: 
After:
* Spin up GE locally
* Append ?devx-api=https://graphexplorerapi-staging.azurewebsites.net to change the destination
* open the chats node
* Notice children in the chats node have their documentation showing
=> Fix: Show documentation URL for supported Resource Explorer items

package-lock.json, package.json, src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/ResourceLink.tsx, src/app/views/sidebar/resource-explorer/collection/PreviewCollection.tsx, src/app/views/sidebar/resource-explorer/command-options/CommandOptions.tsx, src/store/index.ts
When the store is not initialized to start with an empty collections list, and the network call is slow, the page breaks.
This change guarantees that an empty list is initialised so that even on slow internet the resources are prepopulated and the paths do not break.
=> Fix: Ensure collections are initiated in store

src/app/views/sidebar/resource-explorer/resource-explorer.utils.ts
Fixes #2629 
To ensure that items have documentation, a previous update made sure that when resource links are being rendered, the DocumentationService would get the documentation for the rendering item. This works, however, it takes a visible performance hit when the page is forced to re-render multiple times e.g when doing a search.
It makes sense to force the tree to get the documentation at the point of creating the tree so that all the items always show up on render with their documentation.
* Run GE locally on the branch
* Open resource explorer
* Notice that documenation for GET chats exists
* In the search box, write something like 'device m' notice that the page says there's nothing to see
* Backspace slowly and notice the app doesn't …
=> Fix: Get documentation on resource render

src/app/views/query-response/snippets/Snippets.tsx
fixes #2741 
* checkout branch and launch GE locally
* Navigate to code snippets tab
* Change screen dimensions to fit that of a mobile device
* Observe fix
=> Fix: Add overflow option for code snippet languages tab

src/app/views/query-runner/query-input/auto-complete/auto-complete.util.ts
Fixes #2756
The ABNF parser is unable to correctly validate the characters in the URL and crashes. 
Adding a try catch block ensures the page fails gracefully since a failure in validation should not break the experience
* Run Graph Explorer
* In the address bar, write `https://graph.microsoft.com/v1.0/me/💕`
* Page does not crash
=> Fix: Support unicode characters

package-lock.json, package.json
The current msal-browser version 3.1.0 breaks for some users as highlighted in [issue 2895](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2895)
Upgrading to the latest version 3.5.0 ensures we have their needs covered since version 3.2.0 fixes their problem as mentioned in the [Msal Browser changelog](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/CHANGELOG.md#320)
=> Hotfix: Upgrade msal-browser version

src/app/services/reducers/permissions-reducer.spec.ts, src/app/services/reducers/permissions-reducer.ts
Fixes #2999 
There was a state reset needed after getting an error when fetching permissions for one endpoint
* Go to [this jolly sand link](https://jolly-sand-0ac78c710-3000.centralus.azurestaticapps.net)
* On the samples search, type goals and pick the first sample available.
* Open the modify permissions tab, and follow the instructions to open the panel
* See that the panel loads
=> Fix: failing permissions panel load

src/app/services/actions/autocomplete-action-creators.spec.ts, src/app/services/actions/autocomplete-action-creators.ts, src/app/services/actions/permissions-action-creator.spec.ts, src/app/services/actions/resource-explorer-action-creators.spec.ts, src/app/services/actions/resource-explorer-action-creators.ts, src/app/services/context/validation-context/ValidationProvider.tsx, src/app/services/reducers/resources-reducer.spec.ts, src/app/services/reducers/resources-reducer.ts, src/app/utils/resources/resources-filter.ts, src/app/utils/resources/resources.json, src/app/views/query-runner/query-input/auto-complete/suffix/SuffixRenderer.tsx, src/app/views/query-runner/query-input/auto-complete/suffix/documentation.ts, src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/collection/postman.util.spec.ts, src/app/views/sidebar/resource-explorer/resource-explorer.utils.spec.ts, src/app/views/sidebar/resource-explorer/resource-explorer.utils.ts, src/modules/cache/index.ts, src/modules/cache/resources.cache.spec.ts, src/modules/cache/resources.cache.ts, src/modules/suggestions/suggestions.ts, src/types/resources.ts, src/types/sidebar.ts
Fixes #3011 
GE has been calling the DevX API `openapi/tree` endpoint to get the consolidated open api tree document with both versions. This leads to a huge file. 
Currently the built in Javacript `response.json()` function truncates the content as it parses the response string to JSON. This leads to some of the children not being passed from the browser to the code hence losing some nodes along the way.
This new implementation 
- makes parallel calls to get the content of each version. 
- changes the schema so that the resources in state are grouped by the version
- removes the function that was used to filter nodes based on their version as the items are already versioned
`security/auditLog`
`security/auditLog/queries`
Optional. Ancillary topics, caveats, alternative strategies that …
=> Fix: show all resources

src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx, src/modules/suggestions/suggestions.ts
When typing in `/me/photo/$value`, **$value** was not showing up in the list of suggestions provided.
Previously, adding a `$` appended suggestion would trigger the `=` sign to show properties. This fix isolates the `=` sign addition to the context of the url. This now makes it possible to have `$` sign paths appear as suggestions e.g `$count`, `$value` etc
* Write `me/photo/`
* Notice `$value` in the list of items
=> Fix: show dollar sign paths on autocomplete

src/app/utils/query-url-sanitization.ts, src/app/utils/resources/resources-filter.ts, src/app/views/query-runner/query-input/auto-complete/suffix/documentation.ts
Fixes #3063 
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/f92898d7-d367-4498-a9cf-961952248412
* Check out PR
* Load GE
* Paste test link  `https://canary.graph.microsoft.com/testprodbetatamy-pps-offboarding/me/insights/trending`
* Click anywhere on the page and observe the page doesn't crash
=> Fix: Canary urls crashing

package-lock.json, package.json, src/app/utils/query-parameter-sanitization.ts, src/app/utils/query-url-sanitization.ts, src/app/utils/resources/resources-filter.ts, src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx, src/app/views/query-runner/query-input/auto-complete/suffix/documentation.ts, src/modules/suggestions/suggestions.ts
=> Chore: Release 9.8.0

.github/workflows/linter.yml, src/modules/authentication/AuthenticationWrapper.ts
=> Chore: app migration (add missing variable)

src/app/services/actions/query-action-creator-util.ts, src/app/services/context/validation-context/ValidationProvider.tsx, src/types/enums.ts
Closes #2872 
The query mentioned returns a text/csv response that can be properly handled by the browser. This PR adds text/csv headers as supported headers and enables showing the response as plain text on the response viewer
=> Feature: support text csv

package-lock.json, package.json
Bumps version number to 10.1.0
=> Chore: Update 10.1.0

config/webpackDevServer.config.js, package-lock.json
Removes deprecated properties and updates the Middlewares function
=>   Fix: Update webpack Dev Server config

src/modules/authentication/AuthenticationWrapper.ts, src/modules/authentication/msal-app.ts, src/types/index.d.ts
Use strong types in `src/modules/authentication`. Closes #3187 
* open any files in `src/modules/authentication`
* ensure no use of `any` types
* ensure `npm run test` passes in `src/modules/authentication` without fails
5 `any` counts in 2/10 files
```bash
AuthenticationWrapper.ts:4
msal-app.ts:1
```
```
authentication-error-hints.ts:0
AuthenticationWrapper.spec.ts:0
AuthenticationWrapper.ts:0
authUtils.spec.ts:0
authUtils.ts:0
ClaimsChallenge.ts:0
index.ts:0
interfaces/IAuthenticationWrapper.ts:0
interfaces/IClaimsChallenge.ts:0
msal-app.ts:0
```
=> refactor: use strong types in authentication module

src/modules/authentication/AuthenticationWrapper.ts, src/modules/authentication/msal-app.ts
We've been using the `extraQueryParameters` property to handle the code migration. This handles the `/authorize` path only. To cater for all paths, we need to also use the `tokenQueryParameters` property to make sure that the `/token` path is also taken care of.
* Run the application
* Attempt to log in.
* Check the network calls, 
* Notice the `/token` URL has extra query parameters
=> Fix: add parameters to token request

config/webpack.config.js, src/index.tsx, src/types/index.d.ts
Fix #3221 
updates code to fetch web workers from the correct destination
Updated 
The worker URL functions previously existed but we removed them as we had stopped using the monaco-editor webpack plugin. Once we bundled Monaco, we resumed using the plugin and must have forgotten to update the worker urls. 
Ref: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2615
* Checkout this branch
* Load GE
* Check network tab on developer tools
* Observe 200 OK on editor.worker.js/json.worker.js calls
=> Fix: Monaco 404 errors

src/app/views/query-runner/query-input/auto-complete/suffix/SuffixRenderer.tsx
Closes #3234 
Move getting the resource.version.children values to a function.
=> fix: move getting resource version children to a function

release-please-config.json
Release please is pulling in all commits for the changelog https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/3344. This should hopefully stop it at the last release.
=> chore: add starting commit where changelog commits gathering will stop

azure-pipelines.yml, playwright.config.ts, src/tests/ui/anonymous-experiences/sidebar.spec.ts
Fixes failing resources test.
Updates test to ignore authenticated tests due to MFA restrictions
Authenticated tests will be disabled for now since MFA is required and there's no way to handle this when running headless tests on playwright
=> Fix: Update playwright tests

.eslintrc.js
Linting fails with the rule as it is deprecated and moved to eslint stylistic plugin (https://eslint.style)
https://typescript-eslint.io/rules/indent/
Required to close https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/3362
=> chore: Remove reference to a deprecated rule

src/app/utils/dynamic-sort.spec.ts, src/app/utils/dynamic-sort.ts, src/app/views/query-runner/request/permissions/Permissions.Full.tsx, src/app/views/sidebar/SidebarV9.tsx, src/app/views/sidebar/history/History.tsx, src/app/views/sidebar/history/HistoryV9.tsx
Migrates components in the History tab to fluent UI v9.
Closes #3443
=> feat: migrate the history tab components to fluent UI v9

src/app/views/sidebar/sample-queries/SampleQueriesV9.tsx
Enable processing a clicked query item when signed out for GET and signed in for all http methods.
=> fix: update the sample queries signed in/out click functionality

package.json, src/app/views/common/copy-button/CopyButtonV9.tsx, src/app/views/common/lazy-loader/component-registry/index.tsx, src/app/views/query-runner/QueryRunner.tsx, src/app/views/query-runner/request/RequestV9.tsx, src/app/views/query-runner/request/auth/AuthV9.tsx, src/app/views/query-runner/request/auth/index.ts, src/app/views/query-runner/request/headers/RequestHeadersV9.tsx, src/app/views/query-runner/request/headers/index.ts
Update request body, request header, modify permissions and access token tabs
=> feat: update request body area

src/app/views/common/lazy-loader/component-registry/index.tsx, src/app/views/query-runner/request/permissions/Permission.stylesV9.ts, src/app/views/query-runner/request/permissions/PermissionItemV9.tsx, src/app/views/query-runner/request/permissions/Permissions.QueryV9.tsx, src/app/views/query-runner/request/permissions/columnsV9.tsx, src/app/views/query-runner/request/permissions/index.ts
=> feat: migrate Modify Permissions component to fluent v9

src/app/services/context/resize-context/ResizeContext.tsx, src/app/services/context/resize-context/ResizeProvider.tsx, src/app/views/layout/Layout.tsx, src/app/views/query-runner/request/permissions/Permission.stylesV9.ts, src/app/views/query-runner/request/permissions/PermissionItemV9.tsx, src/app/views/query-runner/request/permissions/Permissions.QueryV9.tsx, src/app/views/query-runner/request/permissions/columnsV9.tsx
- Adds a context that passes the resize values to a component in the request, response and side bar area.
- Adds calculation to infer the height of the permissions tab content and set it appropriately
- Fixes layout of tooltip icons, sets arrows on the tooltips
- General formatting.
=> fix: enhance request permissions tab

src/app/views/common/popups/DrawerWrapper.tsx, src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/collection/APICollection.tsx, src/app/views/sidebar/resource-explorer/collection/CollectionPermissions.tsx, src/app/views/sidebar/resource-explorer/collection/CommonCollectionsPanel.tsx, src/app/views/sidebar/resource-explorer/collection/EditCollectionPanel.tsx, src/app/views/sidebar/resource-explorer/collection/EditScopePanel.tsx
=> fix: correct CTA buttons

src/app/views/sidebar/resource-explorer/collection/EditScopePanel.tsx
Disable Save All button after saving edited scopes
=> fix: disable save all button after saving changes

src/app/views/sidebar/history/History.styles.ts, src/app/views/sidebar/history/History.tsx
Fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_queries/edit/?tempQueryId=39d0a1af-392a-4ee4-94ba-e8c2d52c6efb&id=30640
1. Open URL in web:
2. Navigate till history and activate it.
3. Navigate till history tree and expand it.
4. Try to navigate till tree dots (Actions).
5. Observe the fix.
=> fix: history actions button accessible with keyboard.

src/app/views/common/copy-button/CopyButton.tsx, src/app/views/common/popups/DialogWrapper.tsx, src/app/views/query-runner/query-input/share-query/ShareQuery.tsx
Fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_queries/edit/?tempQueryId=1a372e96-5f51-4c15-88b0-26a65a9df1e3&id=30642&queryId=30642
Fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_queries/edit/?tempQueryId=1a372e96-5f51-4c15-88b0-26a65a9df1e3&id=30687&queryId=30642
1. Open URL in web
3. Navigate till share query and activate it.
4. Observe the focus remains in dialog
###Test 2
1. Turn on narraror.
2. Open URL in web
3. Graph explorer page will open.
4. Navigate till share query and activate it.
5. Navigate to copy button and activate it.
6. Observe the …
=> fix: accessibility issues on share query dialog

src/app/views/query-response/QueryResponse.tsx
Fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_queries/edit/?tempQueryId=1a372e96-5f51-4c15-88b0-26a65a9df1e3&id=30720&queryId=30642
1. Open URL in web
3. Navigate till expand button and activate it.
4. Navigate till close button and activate it or press esc key to close the dialog.
5. Observe the fix
=> fix: closing expand dialog returns focus to expand button

src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/collection/APICollection.tsx
Fixes
1. Open URL in web
3. Navigate till My API Collection button and activate it.
4. Press on Close button.
5. Observe the focus return to My API Collection button.
1. Open URL in web
3. Add items to collection using + buttons on API Explorer.
4. Navigate till My API Collection button and activate it.
5. Navigate to Edit Collection button and activate it.
6. Press on Back button.
8. Observe the focus return to Edit collection button
=> fix: return focus to previous element on close/back button

src/app/views/layout/LayoutStyles.tsx, src/app/views/query-response/pivot-items/pivot-item.tsx, src/app/views/sidebar/Sidebar.tsx, src/app/views/sidebar/history/History.styles.ts, src/app/views/sidebar/resource-explorer/resourceExplorerStyles.ts, src/app/views/sidebar/sample-queries/SampleQueries.styles.ts, src/app/views/sidebar/sample-queries/SampleQueries.tsx
fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_queries/edit/?tempQueryId=39d0a1af-392a-4ee4-94ba-e8c2d52c6efb&id=30685&queryId=30685
fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_queries/edit/?tempQueryId=39d0a1af-392a-4ee4-94ba-e8c2d52c6efb&id=30722&queryId=30685
fixes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_queries/edit/?tempQueryId=1a372e96-5f51-4c15-88b0-26a65a9df1e3&id=30723&queryId=30642
Settings > display resolution > 1280x 768>
browser-zoom to 200%> refresh the page.
1. Inspect the page.
2. Zoom till 200%.
3. Set display resolution to 320x 250px
4. …
=> fix: components visible at various page resolutions/zoom sizes

src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx, src/app/views/sidebar/resource-explorer/collection/EditScopePanel.tsx, src/app/views/sidebar/resource-explorer/resourceExplorerStyles.ts
Closes https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_workitems/edit/30737/?view=edit
Also fixes misaligned action buttons on resource tree
1. Go to url provided
2. Activate My API Collection
3. Navigate to Edit Scope
4. Activate and using keyboard or mouse, check items
5. Observe the Change scope dropdown gets activated and announced.
=> fix: announce changed scope activation after selecting checkbox items

src/app/services/slices/snippet.slice.ts, src/app/views/query-response/snippets/Snippets.tsx
fixes #3766 
* Check out branch
* Load Graph Explorer
* Select Code Snippets tab
* Select any sample query
* Observe snippet refreshes
=> fix: code snippet loads when a sample is selected

src/app/views/sidebar/sample-queries/SampleQueries.tsx
Fixes #3813 
* Load Graph Explorer
* Select any sample like GET list all applications with count
* Select share query button
* Paste link on a new tab and edit this part of the URL `https://developer.microsoft.com/graph/graph-explorer?` and replace with the url you're using to test i.e. `http://localhost:3000` or the calm-wave link
* Observe fix
=> fix: Add check for shared query url on page load

.github/release-please.yml, .github/workflows/release-please-master.yml
Move off of PATs, use GH app token.
Commit to dev. Success is if a release PR is automatically made after the commit to dev.
=> chore: update release please to use gh app token
